import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync,readdirSync} from 'node:fs';import {join} from 'node:path';
function walk(dir,out=[]){for(const e of readdirSync(dir,{withFileTypes:true})){const p=join(dir,e.name);e.isDirectory()?walk(p,out):out.push(p)}return out}
test('all rendered internal links and fragments resolve',()=>{const pages=walk('dist').filter(f=>f.endsWith('.html'));assert.ok(pages.length>=44);for(const file of pages){const html=readFileSync(file,'utf8');for(const [,href] of html.matchAll(/href="([^"]+)"/g)){if(href.startsWith('#')){assert.ok(html.includes(`id="${href.slice(1)}"`),`${file}: missing local fragment ${href}`);continue}if(!href.startsWith('/')||href.startsWith('//'))continue;const [path,hash]=href.split('#'),cleanPath=path.split('?')[0],target=cleanPath==='/'?'dist/index.html':`dist${cleanPath}/index.html`;if(!existsSync(target)&&!existsSync('dist'+cleanPath))assert.fail(`${file}: broken ${href}`);if(hash){const targetHtml=readFileSync(target,'utf8');assert.ok(targetHtml.includes(`id="${hash}"`),`${file}: missing fragment ${href}`)}}}});
test('guide calls to action open the matching tools',()=>{const expected={
 'kira-carpani-nedir':'/hesaplama/kira-carpani','ev-pahali-mi':'/ev-analizi','net-kira-getirisi':'/hesaplama/net-kira','reel-konut-getirisi':'/hesaplama/reel-getiri','ev-mi-mevduat-mi':'/karsilastir','konut-kredisi-maliyeti':'/kredi-hesaplama#kredi','tapu-kontrolu':'/kontrol-listesi','iskan-kat-mulkiyeti':'/kontrol-listesi','deprem-riski-kontrolu':'/resmi-kontroller','aidat-borc-kontrolu':'/hesaplama/net-kira','kiracili-ev-almak':'/kontrol-listesi','brut-net-metrekare':'/hesaplama/metrekare','ilan-fiyati-pazarlik':'/ev-analizi','emlak-alim-masraflari':'/hesaplama/alim-maliyeti','konut-endeksi-okuma':'/veri'};for(const[slug,href]of Object.entries(expected)){const html=readFileSync(`dist/rehber/${slug}/index.html`,'utf8');assert.ok(html.includes(`href="${href}"`),`${slug}: wrong CTA`)}});
test('SEO and security delivery files are generated',()=>{for(const p of ['dist/sitemap.xml','dist/robots.txt','dist/_headers','dist/_redirects','dist/404.html'])assert.ok(existsSync(p),p);const sitemap=readFileSync('dist/sitemap.xml','utf8');assert.ok(sitemap.includes('/sehirler/istanbul'));assert.ok(!sitemap.includes('/haberler'));assert.match(readFileSync('dist/index.html','utf8'),/<link rel="canonical" href="https:\/\/konutseyir.com"/)});
test('news pages are noindex and explicitly ad-free',()=>{for(const p of ['dist/haberler/index.html','dist/haberler/haber/index.html']){const html=readFileSync(p,'utf8');assert.match(html,/name="robots" content="noindex,follow"/);assert.match(html,/data-ad-free="true"/);assert.doesNotMatch(html,/adsbygoogle|doubleclick\.net|pagead2\.googlesyndication\.com/)}});
test('contact, privacy and cookie disclosures are published',()=>{assert.match(readFileSync('dist/iletisim/index.html','utf8'),/iletisim@konutseyir\.com/);assert.match(readFileSync('dist/gizlilik/index.html','utf8'),/Google AdSense/);assert.match(readFileSync('dist/cerez-politikasi/index.html','utf8'),/Google AdSense çerezleri/)});
test('installable app icons are generated',()=>{for(const p of ['dist/icon-192.png','dist/icon-512.png','dist/icon-maskable-512.png','dist/apple-touch-icon.png'])assert.ok(existsSync(p),p);const manifest=readFileSync('dist/manifest.webmanifest','utf8');assert.match(manifest,/icon-maskable-512\.png/);assert.match(readFileSync('dist/index.html','utf8'),/apple-touch-icon\.png/)});
test('all guides are comprehensive articles',()=>{const dirs=readdirSync('dist/rehber',{withFileTypes:true}).filter(x=>x.isDirectory());assert.equal(dirs.length,15);for(const dir of dirs){const html=readFileSync(`dist/rehber/${dir.name}/index.html`,'utf8'),text=html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();assert.ok(text.split(' ').length>=300,`${dir.name}: article is too short`)}});
test('structured data identifies the publisher, articles and breadcrumbs',()=>{const home=readFileSync('dist/index.html','utf8'),guide=readFileSync('dist/rehber/kira-carpani-nedir/index.html','utf8');assert.match(home,/"@type":"Organization"/);assert.match(home,/"@type":"WebSite"/);assert.match(home,/"logo":"https:\/\/konutseyir\.com\/icon-512\.png"/);assert.match(guide,/"@type":"Article"/);assert.match(guide,/"@type":"BreadcrumbList"/);assert.match(guide,/property="og:type" content="article"/)});
test('focused calculator pages publish explanatory content and FAQ schema',()=>{for(const slug of ['kira-carpani','net-kira','metrekare','reel-getiri','alim-maliyeti']){const html=readFileSync(`dist/hesaplama/${slug}/index.html`,'utf8');assert.match(html,/"@type":"FAQPage"/,slug);assert.match(html,/KonutSeyir Editoryal Ekibi/,slug)}const rent=readFileSync('dist/hesaplama/kira-carpani/index.html','utf8');assert.match(rent,/Yıllık kira artış varsayımı/);assert.match(rent,/Yıllara göre kira projeksiyonu/)});
