'use client';
import {useState} from 'react';
import {Header,Footer} from '../../../components/site-chrome';

type NewsItem={slug:string;title:string;summary:string;sourceName:string;sourceUrl:string;publishedAt:string;category:string|null};
const formatDate=(value:string)=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(value));
export default function NewsAdmin(){
 const[password,setPassword]=useState(''),[authenticated,setAuthenticated]=useState(false),[items,setItems]=useState<NewsItem[]>([]),[date,setDate]=useState(''),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 const load=async(pass=password,filter=date,nextOffset=0,append=false)=>{setLoading(true);setMessage('');try{const query=new URLSearchParams({limit:'50',offset:String(nextOffset)});if(filter)query.set('date',filter);const response=await fetch('/api/admin/news?'+query,{headers:{'X-Admin-Password':pass},cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'İstek başarısız.');setAuthenticated(true);setItems(current=>append?[...current,...(data.items||[])]:data.items||[]);setOffset(nextOffset);setHasMore(Boolean(data.hasMore));setMessage(String(data.total)+' haber bulundu.')}catch(error){setAuthenticated(false);setItems([]);setMessage(error instanceof Error&&error.message==='invalid_password'?'Şifre hatalı.':error instanceof Error&&error.message==='admin_password_not_configured'?'Yönetici şifresi sunucuya tanımlanmamış.':error instanceof Error&&error.message==='too_many_attempts'?'Çok sayıda hatalı giriş denemesi. 15 dakika sonra tekrar deneyin.':'Haber listesi alınamadı.')}finally{setLoading(false)}};
 const remove=async(item:NewsItem)=>{if(!confirm('“'+item.title+'” haberi kalıcı olarak silinsin mi?'))return;setLoading(true);try{const response=await fetch('/api/admin/news/'+encodeURIComponent(item.slug),{method:'DELETE',headers:{'X-Admin-Password':password}}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'delete_failed');setItems(current=>current.filter(row=>row.slug!==item.slug));setMessage('Haber silindi.')}catch{setMessage('Haber silinemedi. Şifreyi ve bağlantıyı kontrol edin.')}finally{setLoading(false)}};
 return <><Header back/><main className="inner ad-free-page"><div className="page-title"><p className="eyebrow">YÖNETİM</p><h1>Haber yönetimi</h1><p>RSS ve resmî kaynaklardan alınan haberleri tarihe göre listeleyin ve gerekirse silin.</p></div>{!authenticated?<form className="panel" onSubmit={event=>{event.preventDefault();void load(password,date,0,false)}}><label htmlFor="news-admin-password">Yönetici şifresi</label><div className="news-toolbar"><input id="news-admin-password" type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password" inputMode="numeric" maxLength={64} required/><button type="submit" disabled={loading}>{loading?'Kontrol ediliyor…':'Giriş yap'}</button></div></form>:<><section className="panel"><div className="news-toolbar"><label>Tarih <input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button type="button" disabled={loading} onClick={()=>void load(password,date,0,false)}>Listele</button><button type="button" onClick={()=>{setPassword('');setAuthenticated(false);setItems([]);setMessage('Oturum kapatıldı.')}}>Çıkış</button></div></section><div className="news-list">{items.map(item=><article key={item.slug}><div><span>{item.category||'Haber'} · {item.sourceName} · {formatDate(item.publishedAt)}</span><h2>{item.title}</h2><p>{item.summary}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Kaynağı aç</a></div><button type="button" disabled={loading} onClick={()=>void remove(item)}>Sil</button></article>)}</div>{hasMore&&<button type="button" disabled={loading} onClick={()=>void load(password,date,offset+50,true)}>Daha eski haberleri getir</button>}</>}{message&&<p role="status" aria-live="polite">{message}</p>}</main><Footer/></>;
}
