import {ArrowDown, ArrowUpRight, BadgeCheck, BarChart3, Calculator as CalculatorIcon, Database, SearchCheck, ShieldCheck} from 'lucide-react';
import {Header,Footer} from '../components/site-chrome';
import {Calculator,Credit,Deposit} from '../components/calculator';

export default function Home(){return <><Header/><main>
  <section className="hero">
    <div className="hero-copy"><div className="trust-label"><BadgeCheck size={16}/> Şeffaf hesap · Kaynağı belli veri</div><p className="eyebrow">KONUT KARAR DESTEK PLATFORMU</p><h1>Bir evin fiyatından <em>daha fazlasını</em> görün.</h1><p className="lead">Net kira gelirini, tüm giderleri ve reel getiriyi tek ekranda hesaplayın. Konutu mevduat ve altınla aynı sermaye üzerinden karşılaştırın.</p><div className="hero-actions"><a className="primary-link" href="#analiz">İlanımı analiz et <ArrowDown size={17}/></a><a className="text-link" href="/veri">Veriler nereden geliyor? <ArrowUpRight size={16}/></a></div><div className="hero-proof"><span><ShieldCheck/> Üyelik gerektirmez</span><span><CalculatorIcon/> Tarayıcıda hesaplanır</span><span><Database/> Resmî kaynaklarla desteklenir</span></div></div>
    <aside className="hero-preview" aria-label="Örnek konut analizi"><div className="preview-top"><div><span>ÖRNEK SENARYO</span><strong>5.000.000 TL konut</strong></div><span className="preview-badge">30.000 TL kira</span></div><div className="preview-score"><span>Yıllık net kira geliri</span><strong>300.000 <small>TL</small></strong><p>200.000 TL alım masrafı, 1 ay boşluk ve 30.000 TL yıllık gider sonrası</p></div><div className="preview-grid"><div><span>Net getiri</span><b>%5,77</b></div><div><span>Geri dönüş</span><b>17,3 yıl</b></div><div><span>Net m²</span><b>50.000 TL</b></div><div><span>Reel getiri</span><b className="negative-text">%-3,11</b></div></div><div className="preview-note"><BarChart3 size={18}/><span>Reel getiri varsayımı: konut %25 artış, yıllık enflasyon %30 ve 300.000 TL net kira geliri.</span></div></aside>
  </section>
  <section className="value-strip"><div><span>01</span><p><b>İlanı girin</b>Fiyat, metrekare, kira ve giderler</p></div><div><span>02</span><p><b>Net sonucu görün</b>TL, yüzde ve geri dönüş süresi</p></div><div><span>03</span><p><b>Alternatiflerle kıyaslayın</b>Mevduat, altın ve enflasyon</p></div></section>
  <div className="inner"><Calculator/><div className="section-heading"><p className="eyebrow">TAMAMLAYICI HESAPLAR</p><h2>Finansman ve nakit getirisi</h2><p>Konut kararının iki kritik parçasını ayrı, anlaşılır hesaplarla kontrol edin.</p></div><div className="tool-grid"><Deposit/><Credit/></div><section id="kontrol" className="official-section"><div><p className="eyebrow">RESMÎ KONTROLLER</p><h2>Satın almadan önce doğrulayın</h2><p>Parsel ve bölgesel tehlike bilgileri bina dayanıklılığını göstermez. Tapu, iskân ve teknik incelemeyi ayrıca tamamlayın.</p></div><div className="official-links"><a href="https://parselsorgu.tkgm.gov.tr/" target="_blank" rel="noreferrer"><SearchCheck/><span><b>TKGM Parsel Sorgu</b><small>Ada ve parsel bilgisini doğrulayın</small></span><ArrowUpRight/></a><a href="https://tdth.afad.gov.tr/" target="_blank" rel="noreferrer"><ShieldCheck/><span><b>AFAD Tehlike Haritası</b><small>Bölgesel deprem tehlikesini inceleyin</small></span><ArrowUpRight/></a><a href="/kontrol-listesi"><BadgeCheck/><span><b>Alım Kontrol Listesi</b><small>Hiçbir kritik adımı atlamayın</small></span><ArrowUpRight/></a></div></section></div>
  </main><Footer/></>}
