import {Header,Footer} from '../../components/site-chrome';
import {Calculator} from '../../components/calculator';

export default function HomeAnalysis(){return <><Header back/><main className="inner focused-tool-page analysis-page">
 <div className="page-title"><p className="eyebrow">KONUT YATIRIM ANALİZİ</p><h1>Bir konutun yatırım mantığını tek tabloda inceleyin</h1><p>İlan fiyatını tek başına değerlendirmek yerine toplam alım maliyetini, sürdürülebilir net kirayı, metrekare fiyatını, geri dönüş süresini ve enflasyon sonrası sonucu aynı hesapta görün. Aşağıdaki araç yatırım kararı vermez; girdiğiniz varsayımların finansal sonucunu görünür hale getirir.</p></div>
 <section className="analysis-roadmap"><article><span>01</span><div><h2>Gerçek maliyeti bulun</h2><p>Satış fiyatına tapu, komisyon, zorunlu tadilat ve diğer başlangıç giderlerini ekleyin.</p></div></article><article><span>02</span><div><h2>Brüt değil net kirayı ölçün</h2><p>Boş kalma, malike ait giderler ve vergi sonrası yıllık nakit akışını hesaplayın.</p></div></article><article><span>03</span><div><h2>Satın alma gücünü sınayın</h2><p>Konut değer değişimini enflasyon ve alternatif yatırım varsayımlarıyla aynı dönemde karşılaştırın.</p></div></article></section>
 <nav className="tool-jumps" aria-label="Ayrı hesaplama araçları"><a href="/hesaplama/kira-carpani">Kira çarpanı</a><a href="/hesaplama/net-kira">Net kira</a><a href="/hesaplama/metrekare">Metrekare</a><a href="/hesaplama/reel-getiri">Reel getiri</a><a href="/hesaplama/alim-maliyeti">Alım maliyeti</a><a href="/hesaplama/tapu-harci">Tapu harcı</a><a href="/hesaplama/emlak-komisyonu">Emlak komisyonu</a><a href="/hesaplama/kira-artis-orani">Kira artışı</a><a href="/hesaplama/altin-bazli-konut">Altın / konut</a><a href="/hesaplama/hisseli-tapu">Hisseli tapu</a></nav>
 <Calculator/>
 <section className="analysis-editorial"><h2>Sonuçları hangi sırayla okumak gerekir?</h2><p>İlk olarak toplam başlangıç yatırımına bakın. Bir konutun ekonomik maliyeti yalnız ilan fiyatı değildir; satın alma sırasında ortaya çıkan zorunlu giderler başlangıç sermayesini büyütür. Ardından yıllık net kira gelirini ve net kira getirisini inceleyin. Bu iki değer, konutun düzenli nakit akışını satış fiyatından bağımsız biçimde anlamanıza yardım eder.</p><p>Kira çarpanı hızlı bir karşılaştırma ölçüsüdür fakat tek başına değerleme değildir. Aynı mahallede bile bina yaşı, kat, cephe, otopark, hukuki durum, bakım ihtiyacı ve kiracı profili fiyatı değiştirebilir. Bu nedenle metrekare fiyatı ile kira çarpanını yakın ve gerçekten karşılaştırılabilir emsaller üzerinde birlikte kullanın.</p><h2>Bir yıllık senaryo neyi gösteriyor?</h2><p>Bir yıllık bölüm, girdiğiniz konut fiyat değişimi ve net kira ile dönem sonu varsayımsal değeri hesaplar. Aynı başlangıç sermayesinin mevduat ve altın senaryolarındaki sonucunu da yan yana gösterir. Buradaki oranlar gelecek tahmini değildir. Özellikle TCMB mevduat istatistiği belirli bir bankanın müşteri teklifini temsil etmez; karşılaştırmada kendi bankanızın brüt oranını kullanmanız gerekir.</p><p>Reel sonuç, nominal TL tutarını enflasyon varsayımına göre başlangıç gününün satın alma gücüne çevirir. Böylece yalnız “kaç TL kazandım?” sorusuna değil, “satın alma gücüm arttı mı?” sorusuna da yaklaşabilirsiniz. Uzun vadeli karar için aynı hesabı farklı kira, değer artışı, enflasyon ve boş kalma varsayımlarıyla tekrarlamak daha sağlıklıdır.</p></section>
 </main><Footer/></>}