import {useState} from 'react';
import {grossRentMetrics,netRentMetrics,squareMeterMetrics,realEstateReturn,purchaseCostMetrics} from '../lib/finance.mjs';
import {money} from './calculator';

type Fields=Record<string,number>;
const pct=(n:number)=>`%${n.toLocaleString('tr-TR',{maximumFractionDigits:2})}`;

function Input({label,value,onChange,hint}:{label:string,value:number,onChange:(v:number)=>void,hint?:string}){
 return <label className="calc-field"><span>{label}</span><input type="number" step="any" value={Number.isNaN(value)?'':value} onChange={e=>onChange(e.target.value===''?NaN:Number(e.target.value))}/>{hint&&<small>{hint}</small>}</label>
}
function Safe({fn,children}:{fn:()=>any,children:(r:any)=>React.ReactNode}){
 try{return <>{children(fn())}</>}catch(e){return <p className="error" role="alert">{(e as Error).message}</p>}
}
function Tool({initial,labels,calculate,children,note}:{initial:Fields,labels:Array<[string,string,string?]>,calculate:(p:Fields)=>any,children:(r:any)=>React.ReactNode,note:string}){
 const[p,set]=useState(initial);
 return <section className="focused-calculator" aria-live="polite"><div className="focused-form"><div className="fields">{labels.map(([key,label,hint])=><Input key={key} label={label} hint={hint} value={p[key]} onChange={value=>set(current=>({...current,[key]:value}))}/>)}</div><button className="secondary" type="button" onClick={()=>set(initial)}>Örneğe sıfırla</button></div><div className="focused-results"><Safe fn={()=>calculate(p)}>{children}</Safe><p className="focused-note">{note}</p></div></section>
}
function Results({items,hero}:{items:Array<[string,string]>,hero:[string,string,string?]}){return <><div className="focused-result-hero"><span>{hero[0]}</span><strong>{hero[1]}</strong>{hero[2]&&<b>{hero[2]}</b>}</div><dl className="focused-result-list">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></>}

export function RentMultiplierCalculator(){return <Tool initial={{price:5000000,rent:30000}} labels={[["price","Satış fiyatı (TL)"],["rent","Aylık brüt kira (TL)"]]} calculate={p=>grossRentMetrics(p.price,p.rent)} note="Brüt hesap; boş kalma, aidat, bakım ve vergi düşülmez. Gerçek karar için net kira aracını da kullanın.">{r=><Results hero={["Brüt kira çarpanı",r.multiplierYears===null?'Hesaplanamaz':`${r.multiplierYears.toFixed(1)} yıl`,r.multiplierMonths===null?undefined:`${r.multiplierMonths.toFixed(1)} ay`]} items={[["Yıllık brüt kira",money(r.annualRent)],["Brüt kira getirisi",pct(r.grossYield)]]}/>}</Tool>}

export function NetRentCalculator(){return <Tool initial={{price:5000000,costs:200000,rent:30000,vacancy:1,expenses:30000,tax:0}} labels={[["price","Satış fiyatı (TL)"],["costs","Alım masrafları (TL)"],["rent","Aylık kira (TL)"],["vacancy","Yılda boş kalan ay","0–12 ay"],["expenses","Yıllık giderler (TL)","Malik aidatı, bakım, sigorta"],["tax","Yıllık kira gelir vergisi (TL)","Kendi durumunuza göre hesaplanan tutar"]]} calculate={p=>netRentMetrics(p.price,p.costs,p.rent,p.vacancy,p.expenses,p.tax)} note="Net getiri, alım masrafları dahil toplam başlangıç yatırımına bölünür. Vergi alanındaki 0 değeri muafiyet beyanı değildir.">{r=><Results hero={["Yıllık net kira",money(r.net),`${pct(r.netYield)} net getiri`]} items={[["Toplam başlangıç yatırımı",money(r.capital)],["Yıllık brüt kira",money(r.gross)],["Boş kalma kaybı",money(r.emptyLoss)],["Tahsil edilebilir kira",money(r.collected)],["Aylık ortalama net kira",money(r.monthlyNet)],["Net geri dönüş",r.paybackYears===null?'Pozitif net kira yok':`${r.paybackYears.toFixed(1)} yıl`]]}/>}</Tool>}

export function SquareMeterCalculator(){return <Tool initial={{price:5000000,area:100}} labels={[["price","Satış fiyatı (TL)"],["area","Karşılaştırılacak alan (m²)","Net alanı net alanla, brüt alanı brüt alanla kıyaslayın."]]} calculate={p=>squareMeterMetrics(p.price,p.area)} note="İlanlardaki brüt alan tanımı standart olmayabilir. Hesabın anlamlı olması için emsallerde aynı alan türünü kullanın.">{r=><Results hero={["Metrekare fiyatı",money(r.pricePerM2),"1 m² için"]} items={[["Satış fiyatı",money(r.price)],["Kullanılan alan",`${r.area.toLocaleString('tr-TR')} m²`]]}/>}</Tool>}

export function RealReturnCalculator(){return <Tool initial={{capital:5200000,growth:25,netRent:300000,saleCosts:0,inflation:30}} labels={[["capital","Toplam başlangıç yatırımı (TL)"],["growth","Konut fiyat değişimi (%)"],["netRent","Yıllık net kira (TL)"],["saleCosts","Dönem sonu satış gideri (TL)"],["inflation","Yıllık enflasyon (%)"]]} calculate={p=>realEstateReturn(p.capital,p.growth,p.netRent,p.saleCosts,p.inflation)} note="Reel tutarlar başlangıç gününün satın alma gücüyle gösterilir. Bu bir yıllık senaryodur; gelecek performans tahmini değildir.">{r=><Results hero={["Reel kâr / zarar",money(r.realProfit),pct(r.realRate)]} items={[["Dönem sonu nominal değer",money(r.end)],["Nominal kâr / zarar",`${money(r.profit)} · ${pct(r.rate)}`],["Enflasyondan arındırılmış değer",money(r.realEnd)]]}/>}</Tool>}

export function PurchaseCostCalculator(){return <Tool initial={{price:5000000,deed:100000,commission:120000,renovation:0,finance:0,other:0}} labels={[["price","Satış fiyatı (TL)"],["deed","Tapu harcı ve döner sermaye (TL)"],["commission","Emlak komisyonu (TL)"],["renovation","Tadilat / taşınma (TL)"],["finance","Ekspertiz ve kredi gideri (TL)"],["other","Diğer başlangıç giderleri (TL)"]]} calculate={p=>purchaseCostMetrics(p.price,p.deed,p.commission,p.renovation,p.finance,p.other)} note="Oranlar ve yükümlülükler işleme göre değişebilir. Burada güncel teklif veya resmî tahakkuk tutarlarını girin.">{r=><Results hero={["Toplam yatırım maliyeti",money(r.total),`${pct(r.costRate)} ek maliyet`]} items={[["Satış fiyatına ek gider",money(r.additional)]]}/>}</Tool>}
