import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Building2,Coins,Info} from 'lucide-react';
import {areaFromValue,cityUnitPrices,dateLabel,goldAssets,parseTrNumber,positive} from '../lib/gold-housing.mjs';

declare global{interface Window{gtag?: (...args:any[])=>void}}
const money=(n:number)=>n.toLocaleString('tr-TR',{maximumFractionDigits:0})+' TL';
export function GoldHousing(){
 const[asset,setAsset]=useState('gram'),[quantity,setQuantity]=useState('250'),[goldValue,setGoldValue]=useState<number|null>(null),[snapshotTime,setSnapshotTime]=useState<string|null>(null),[isSnapshot,setIsSnapshot]=useState(false),[price,setPrice]=useState<number|null>(null),[priceTime,setPriceTime]=useState<string|null>(null),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState('');
 useEffect(()=>{const q=new URLSearchParams(location.search),incoming=q.get('source')==='altinseyir';if(incoming){const a=q.get('asset')||'gram',qty=positive(q.get('quantity'),1000000),pure=positive(q.get('pure_gram'),1000000),ref=positive(q.get('gram_ref_try')),value=positive(q.get('gold_value_try'));if(a in goldAssets)setAsset(a);if(qty)setQuantity(String(qty));const snap=value||(pure&&ref?pure*ref:null);if(snap&&snap<=1e15){setGoldValue(snap);setIsSnapshot(true);setSnapshotTime(q.get('price_at'))}else setMessage('AltınSeyir bağlantısında kullanılabilir bir altın değeri bulunamadı; güncel referans fiyatıyla yaklaşık hesap yapılacak.')}else{const a=q.get('asset');if(a&&a in goldAssets)setAsset(a);const qty=positive(q.get('quantity'),1000000);if(qty)setQuantity(String(qty))}
 let live=true;Promise.allSettled([fetch('/api/gold-price').then(r=>r.ok?r.json():Promise.reject()).then(j=>({price:positive(j?.gram),time:j?.recordedAt||null})),fetch('/api/housing-unit-prices').then(r=>r.ok?r.json():Promise.reject()).then(j=>j?.items||[])]).then(([g,h])=>{if(!live)return;if(g.status==='fulfilled'){setPrice(g.value.price);setPriceTime(g.value.time)}if(h.status==='fulfilled')setRows(h.value)}).finally(()=>live&&setBusy(false));return()=>{live=false}},[]);
 const incoming=typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('source')==='altinseyir';
 const assetInfo=goldAssets[asset as keyof typeof goldAssets];const pureGrams=useMemo(()=>{const n=positive(quantity,1000000);return n?(asset==='bilezik22'?n*assetInfo.pureGrams:n*assetInfo.pureGrams):null},[quantity,asset,assetInfo]);
 const value=goldValue??(pureGrams&&price?pureGrams*price:null);const resultRows=rows.filter(x=>Number.isFinite(Number(x.pricePerM2))&&Number(x.pricePerM2)>0&&value).map(x=>({...x,area:areaFromValue(value,Number(x.pricePerM2))})).filter(x=>x.area!=null).sort((a,b)=>a.pricePerM2-b.pricePerM2);
 function calculate(){const n=positive(quantity,1000000);if(!n){setMessage('Miktar sıfırdan büyük, geçerli bir sayı olmalı.');return}if(!goldValue&&!price){setMessage('Güncel altın fiyatı alınamadı. AltınSeyir’den güncel referans değerini açın.');return}setMessage('');window.gtag?.('event','gold_housing_calculate',{asset,source:incoming?'altinseyir':'direct'});}
 return <div className="gold-housing-page"><section className="gold-housing-panel"><div className="gold-housing-form"><p className="eyebrow"><Coins size={14}/> ALTIN BİRİKİMİ · KONUT ALIM GÜCÜ</p><h2>Altın miktarınızı girin</h2><p>AltınSeyir’den gelen miktar otomatik doldurulur. Doğrudan gelen ziyaretçi de aynı aracı kullanabilir.</p><div className="gold-housing-fields"><label>Altın türü<select value={asset} onChange={e=>setAsset(e.target.value)}>{Object.entries(goldAssets).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><label>Miktar<input inputMode="decimal" type="text" value={quantity} onChange={e=>setQuantity(e.target.value)} aria-label="Altın miktarı"/></label></div><button className="primary-link" type="button" onClick={calculate}>Hesapla <ArrowUpRight size={17}/></button>{message&&<p className="gold-housing-message" role="status">{message}</p>}<small>Doğrudan girişte AltınSeyir’in gram referansı kullanılır. 22 ayar ve ziynet türleri için hesap, saf altın eşdeğerine göre yaklaşık değerdir; işçilik ve alış-satış farkı içermez.</small></div><div className="gold-housing-summary"><div className="gold-summary-icon"><Building2/></div><span>Altın değeri</span><strong>{value?money(value):busy?'Yükleniyor…':'Veri alınamadı'}</strong><small>{isSnapshot?'AltınSeyir’den gelen fiyat görüntüsü':price?'AltınSeyir güncel gram referansı · yaklaşık':'Altın fiyatı kullanılabilir değil'}</small>{snapshotTime&&<small>Altın fiyat zamanı: {dateLabel(snapshotTime)||'Bağlantı zaman bilgisi geçersiz'}</small>}{priceTime&&!isSnapshot&&<small>Fiyat zamanı: {dateLabel(priceTime)||'API zamanı'}</small>}</div></section>
 <section className="gold-housing-results"><header><div><p className="eyebrow">ŞEHİR BAZINDA SONUÇ</p><h2>{quantity||'0'} {assetInfo.label} alım gücü</h2></div><span>Yaklaşık m²</span></header>{busy?<p className="gold-housing-empty">TCMB konut birim fiyatları yükleniyor…</p>:!value?<p className="gold-housing-empty">Altın değeri hesaplanamadı. Güncel fiyat için <a href="https://altinseyir.com/gram-altin" target="_blank" rel="noopener noreferrer">AltınSeyir’i açın</a>.</p>:resultRows.length?<div className="gold-city-list">{resultRows.map(row=><a className="gold-city-row" href={`/sehirler/${row.slug}`} key={row.slug}><span><b>{row.name}</b><small>TCMB ortanca konut birim fiyatı · {row.quarter||'dönem yok'} · {money(Number(row.pricePerM2))}/m²</small></span><strong>{Number(row.area).toLocaleString('tr-TR',{maximumFractionDigits:1})} m²</strong><ArrowUpRight size={16}/></a>)}</div>:<p className="gold-housing-empty">Bu şehirler için henüz kullanılabilir TCMB konut birim fiyatı yok. Seride veri bulunan iller gösterilir; eksik değer tahmin edilmez.</p>}{value&&<p className="gold-housing-note"><Info size={15}/> Formül: Altın TL değeri ÷ TCMB’nin çeyreklik ortanca konut birim fiyatı (TL/brüt m²). Altın ve konut verilerinin dönemleri aynı olmayabilir.</p>}</section>
 <section className="gold-housing-editorial"><p className="eyebrow">HESAPLAMA YÖNTEMİ</p><h2>Altınla kaç metrekare konut alınabilir?</h2><p>Altın birikiminin karşılığı şehirdeki ortanca konut birim fiyatına bölünür. KonutSeyir, TCMB EVDS’nin değerlemesi yapılan konutlara ilişkin TL/brüt m² verisini kullanır. Bu değer ilan fiyatı veya belirli bir evin ekspertizi değildir; yeterli veri bulunmayan şehirlerde sonuç gösterilmez.</p><p>AltınSeyir’den aktarılan altın toplamı değiştirilmeden kullanılır. Bağlantıda toplam değer yoksa verilen saf gram ile gram referansının çarpımı kullanılır; doğrudan girişte güncel gram referansı ve seçilen altın türünün saf gram eşdeğeriyle yaklaşık değer hesaplanır.</p><a href="https://altinseyir.com/altindan-konuta" target="_blank" rel="noopener noreferrer">AltınSeyir altın hesaplamalarına geçin <ArrowUpRight size={15}/></a></section></div>
}
