import {useEffect,useState} from 'react';
import {money} from './calculator';
import {goldPropertyScenario} from '../lib/gold-housing.mjs';
import {useMarketData} from './live-data';

const pct=(n:number)=>`%${n.toLocaleString('tr-TR',{maximumFractionDigits:2})}`;
function N({label,value,onChange,hint,min,max}:{label:string,value:number,onChange:(v:number)=>void,hint?:string,min?:number,max?:number}){return <label className="calc-field"><span>{label}</span><input type="number" step="any" min={min} max={max} value={Number.isNaN(value)?'':value} onChange={e=>onChange(e.target.value===''?0:Number(e.target.value))}/>{hint&&<small>{hint}</small>}</label>}
function Box({children}:{children:React.ReactNode}){return <section className="focused-calculator"><div className="focused-form">{children}</div></section>}

export function DeedFeeCalculator(){
 const[p,s]=useState({price:5000000,revolving:0}); const buyer=p.price*.02+p.revolving,seller=p.price*.02;
 return <Box><h2>Tapu harcı ve döner sermaye</h2><div className="fields"><N label="Beyan edilen satış bedeli (TL)" value={p.price} onChange={v=>s({...p,price:v})}/><N label="Döner sermaye bedeli (TL)" value={p.revolving} onChange={v=>s({...p,revolving:v})} hint="Tarifeye ve işleme göre değişebildiği için güncel tahakkuk tutarını girin."/></div><div className="metric-row"><p>Alıcı tapu harcı (%2) <b>{money(p.price*.02)}</b></p><p>Satıcı tapu harcı (%2) <b>{money(seller)}</b></p><p>Alıcı toplamı <b>{money(buyer)}</b></p><p>İşlem toplamı <b>{money(buyer+seller)}</b></p></div><small>Satış bedeli emlak vergisi değerinden düşük olamaz. Döner sermaye tutarı sabit yüzde değildir.</small></Box>
}
export function CommissionCalculator(){
 const[p,s]=useState({price:5000000,vat:20}); const side=p.price*.02,vat=side*p.vat/100,total=side+vat;
 return <Box><h2>Emlak danışmanı hizmet bedeli</h2><div className="fields"><N label="Satış bedeli (TL)" value={p.price} onChange={v=>s({...p,price:v})}/><N label="KDV (%)" value={p.vat} onChange={v=>s({...p,vat:v})}/></div><div className="metric-row"><p>Bir taraf için tavan (%2) <b>{money(side)}</b></p><p>KDV <b>{money(vat)}</b></p><p>Bir taraf KDV dahil <b>{money(total)}</b></p><p>İki taraf toplam tavan <b>{money(total*2)}</b></p></div><small>Satış aracılık hizmet bedeli KDV hariç satış bedelinin %4'ünü aşamaz; aksi kararlaştırılmadıkça taraflar arasında eşit paylaşılır.</small></Box>
}
export function RentIncreaseCalculator(){
 const[p,s]=useState({rent:30000,rate:Number.NaN});
 const cpi=useMarketData().find(item=>item.series==='cpi');
 const liveRate=cpi?.twelveMonthAverage??null;
 const period=cpi?.twelveMonthAveragePeriod??cpi?.period??'';
 useEffect(()=>{if(liveRate!==null&&Number.isFinite(liveRate))s(x=>({...x,rate:liveRate}))},[liveRate]);
 const validRate=Number.isFinite(p.rate),next=validRate?p.rent*(1+p.rate/100):null;
 return <Box><h2>Kira artış oranı hesaplama</h2><div className="fields"><N label="Mevcut aylık kira (TL)" value={p.rent} onChange={v=>s({...p,rent:v})}/><N label="TÜFE 12 aylık ortalama (%)" value={p.rate} onChange={v=>s({...p,rate:v})} hint={period?'Resmî TÜFE 12 aylık ortalama verisi: '+period+'. İsterseniz oranı değiştirebilirsiniz.':'Resmî veri yüklenemezse sözleşmenin yenilendiği aya ait TÜİK oranını girin.'}/></div><div className="metric-row"><p>Azami artış tutarı <b>{next===null?'Resmî oran bekleniyor':money(next-p.rent)}</b></p><p>Artış sonrası kira <b>{next===null?'—':money(next)}</b></p></div><small>Kaynak: <a href="https://veriportali.tuik.gov.tr/" target="_blank" rel="noreferrer">TÜİK TÜFE</a> / TCMB EVDS. Oran, son 12 aylık TÜFE endeksi ortalamasının önceki 12 aylık ortalamaya göre değişimidir. Dönem: {period||'henüz alınamadı'}. Konut kiraları için sözleşme ve mevzuat durumunu ayrıca kontrol edin.</small></Box>
}
export function GoldPropertyCalculator(){
 const[p,s]=useState({price:5000000,gram:0,ownedGrams:250,downPaymentRate:20}); const[auto,setAuto]=useState<number|null>(null); const[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;const query=new URLSearchParams(window.location.search);const fromGold=query.get('source')==='altinseyir';const parseSnapshot=(key:string)=>{const raw=query.get(key);if(!raw||!/^\d+(?:\.\d+)?$/.test(raw))return null;const value=Number(raw);return Number.isFinite(value)&&value>0&&value<=1000000?value:null};const gramsFromGold=fromGold?parseSnapshot('pure_gram'):null;const refFromGold=fromGold?parseSnapshot('gram_ref_try'):null;const totalFromGold=fromGold?parseSnapshot('gold_value_try'):null;const goldRef=refFromGold??(gramsFromGold&&totalFromGold?totalFromGold/gramsFromGold:null);if(gramsFromGold||goldRef)s(x=>({...x,...(gramsFromGold?{ownedGrams:gramsFromGold}:{}),...(goldRef?{gram:goldRef}:{})}));const load=async()=>{setLoading(true);for(const url of ['/api/gold-price','https://api.altinseyir.com/api/prices']){try{const r=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)continue;const j=await r.json();const g=Number(j?.gram??j?.price?.gram);if(Number.isFinite(g)&&g>0){if(live){setAuto(g);s(x=>({...x,gram:goldRef??g}));setLoading(false)}return}}catch{}}if(live){setAuto(null);setLoading(false)}};load();return()=>{live=false}},[]);
 const scenario=goldPropertyScenario({price:p.price,gramPrice:p.gram,ownedGrams:p.ownedGrams,downPaymentRate:p.downPaymentRate}),show=(value:number|undefined)=>scenario?money(value||0):'—',altinUrl='https://altinseyir.com/altindan-konuta?source=konutseyir&gold_type=gram&gold_quantity='+encodeURIComponent(String(p.ownedGrams)),sqmUrl='/altinla-konut/?source=konutseyir&asset=gram&quantity='+encodeURIComponent(String(p.ownedGrams));
 return <Box><h2>Altın birikiminiz konut bütçesinde ne ifade ediyor?</h2><p className="tool-intro">Konut fiyatını gram altına çevirin; elinizdeki altının hedef peşinatı ne ölçüde karşıladığını ve aynı peşinat oranıyla ulaşılabilecek yaklaşık konut bütçesini görün.</p><div className="fields"><N label="Konut değeri (TL)" value={p.price} onChange={v=>s({...p,price:v})} min={1}/><N label="Gram altın referans fiyatı (TL)" value={p.gram} onChange={v=>s({...p,gram:v})} min={0} hint={loading?'AltınSeyir referans fiyatı yükleniyor…':auto?`AltınSeyir referans verisi otomatik alındı: ${money(auto)}.`:'Canlı fiyat şu anda alınamadı. Güncel gram referans fiyatını elle girebilirsiniz.'}/><N label="Elinizdeki gram altın" value={p.ownedGrams} onChange={v=>s({...p,ownedGrams:v})} min={0}/><N label="Hedef peşinat oranı (%)" value={p.downPaymentRate} onChange={v=>s({...p,downPaymentRate:v})} min={1} max={100} hint="Bu oran kredi onayı değildir; yalnızca bütçe senaryosudur."/></div>{!scenario&&<p className="error" role="status">Konut ve gram fiyatı pozitif olmalı; peşinat oranı %1 ile %100 arasında olmalı.</p>}<div className="metric-row gold-property-results"><p>Konutun altın karşılığı <b>{scenario?scenario.houseGoldGrams.toLocaleString('tr-TR',{maximumFractionDigits:1})+' gram':'—'}</b></p><p>Altın birikiminizin TL karşılığı <b>{show(scenario?.goldValue)}</b></p><p>Hedef peşinat tutarı <b>{show(scenario?.requiredDownPayment)}</b></p><p>Peşinat karşılama oranı <b>{scenario?'%'+scenario.coverage.toLocaleString('tr-TR',{maximumFractionDigits:1}):'—'}</b></p><p>Kalan peşinat ihtiyacı <b>{show(scenario?.remainingDownPayment)}</b></p><p>Bu peşinat oranıyla konut bütçesi <b>{show(scenario?.reachableBudget)}</b></p></div><div className="gold-deep-links"><a href={sqmUrl}>Eldeki altınla kaç m² alınır? →</a><a href={altinUrl} target="_blank" rel="noreferrer">Altınınız ne kadar konut alıyor? →</a><a href="/hesaplama/altin-bazli-konut/">Altınınız ev peşinatını karşılıyor mu? →</a><a href="https://altinseyir.com/gram-altin" target="_blank" rel="noreferrer">Gram altın fiyatını ve grafiğini incele →</a></div><small>Referans gram fiyatı piyasa göstergesidir; fiziki altının alış/satış farkı ve kredi koşulları sonuçlara dahil değildir.</small></Box>
}
export function ShareCalculator(){
 const[p,s]=useState({area:120,value:6000000,num:1,den:4}); const ratio=p.den>0?p.num/p.den:0;
 return <Box><h2>Hisseli tapu payı</h2><div className="fields"><N label="Toplam alan (m²)" value={p.area} onChange={v=>s({...p,area:v})}/><N label="Taşınmaz değeri (TL)" value={p.value} onChange={v=>s({...p,value:v})}/><N label="Pay" value={p.num} onChange={v=>s({...p,num:v})}/><N label="Payda" value={p.den} onChange={v=>s({...p,den:v})}/></div><div className="metric-row"><p>Pay oranı <b>{pct(ratio*100)}</b></p><p>Matematiksel alan karşılığı <b>{(p.area*ratio).toLocaleString('tr-TR',{maximumFractionDigits:2})} m²</b></p><p>Değer karşılığı <b>{money(p.value*ratio)}</b></p></div><small>Hisseli tapuda bu m² hesabı belirli bir fiziksel bölümün mülkiyetini göstermez. Miras payları için veraset ilamındaki oranları kullanın.</small></Box>
}
