type Section={title:string;paragraphs:string[];bullets?:string[]};
type ToolCopy={sections:Section[];faqs:Array<{q:string,a:string}>};

const copy:Record<string,ToolCopy>={
 'kira-carpani':{sections:[
  {title:'Kira çarpanı neyi ölçer?',paragraphs:['Kira çarpanı, satış fiyatının bugünkü yıllık brüt kiraya oranıdır. 5.000.000 TL fiyat ve aylık 30.000 TL kira için ilk yıl geliri 360.000 TL, sabit kirayla brüt çarpan yaklaşık 13,9 yıldır. Bu, konutun gerçek geri ödeme süresi değil; ilanları aynı ölçekte karşılaştıran ilk eleme göstergesidir.','Kira artışlı projeksiyon her yılın aylık kirasını seçtiğiniz oranla bileşik artırır ve birikimli brüt kirayı hesaplar. Sonuç yasal artış oranı veya gelecek tahmini değildir. Kiracı değişimi, boşluk, tahsilat sorunu ve mevzuat nedeniyle gerçekleşen artış farklı olabilir.']},
  {title:'Brüt ve net geri dönüşü ayırın',paragraphs:['Brüt hesap giderleri görmez. Tapu, komisyon ve tadilat başlangıç yatırımını büyütür; boş kalma, malik aidatı, bakım, sigorta ve kira vergisi elde kalan tutarı azaltır. Bu nedenle karar verirken kira çarpanı aracından sonra net kira hesabını da çalıştırın.','Artışlı kira sonucu paranın zaman değerini de içermez. On yıl sonra tahsil edilen 100.000 TL ile bugün tahsil edilen 100.000 TL aynı satın alma gücüne sahip değildir. Uzun dönem sonucu reel getiri aracıyla enflasyondan arındırın.'],bullets:['Aynı mahallede benzer bina ve net alanı karşılaştırın.','İlan kirası yerine sürdürülebilir tahsil edilebilir kirayı kullanın.','Temel, düşük artış ve sıfır artış senaryolarını ayrı çalıştırın.']},
  {title:'Sonucu nasıl yorumlamalısınız?',paragraphs:['Düşük çarpan her zaman fırsat değildir. Olağan dışı yüksek kira, kiracılı teslim, büyük bakım ihtiyacı veya hukuki belirsizlik fiyatı aşağı çekmiş olabilir. Yüksek çarpan da yalnızca pahalılık anlamına gelmez; oturum talebi, yeni bina veya sınırlı arz fiyatı taşıyabilir.','Tek bir iyi yıl varsayımıyla karar vermeyin. Kira artış oranını düşürerek, bir yıllık boşluk etkisini net kira aracına ekleyerek ve aynı sermayenin stopaj sonrası mevduat sonucunu karşılaştırarak dayanıklılığı ölçün.']}
 ],faqs:[{q:'Kira artış oranı TÜFE’den otomatik alınmalı mı?',a:'Hayır. Yasal kira artış ölçütü ile yıllık TÜFE değişimi aynı seri değildir. Araçtaki oran kullanıcı senaryosudur ve sözleşme ile güncel mevzuat ayrıca doğrulanmalıdır.'},{q:'Kira çarpanında alım masrafı var mı?',a:'Brüt çarpanda yalnız satış fiyatı kullanılır. Alım masrafları ve yıllık giderler için net kira aracını kullanın.'},{q:'Artışlı geri dönüş neden daha kısa çıkıyor?',a:'Her yıl kira bileşik arttığı için birikimli brüt gelir fiyatı daha erken karşılar. Bu sonuç gider, vergi ve paranın zaman değerini içermediğinden tek başına yatırım kararı değildir.'}]},
 'net-kira':{sections:[
  {title:'Net kira hesabının mantığı',paragraphs:['Net yıllık kira; aylık kira × tahsil edilen ay sayısından işletme gideri ve kira gelir vergisinin çıkarılmasıyla bulunur. Net getiri oranında payda satış fiyatı değil, satış fiyatı ile alım masraflarının toplamıdır. Böylece ilanın değil, yatırılan gerçek sermayenin getirisi ölçülür.','Bir aylık boş kalma, küçük bakım ve sigorta giderleri düşük görünse de yıllık getiriyi belirgin biçimde değiştirebilir. Kiracının ödediği olağan aidatı malik giderine tekrar eklemeyin; yalnızca size kalan giderleri yazın.']},
  {title:'Hangi tutarlar girilmeli?',paragraphs:['Alım masrafına tapu, emlak hizmet bedeli, ekspertiz, krediye bağlı başlangıç giderleri ve kiraya vermek için zorunlu tadilat eklenebilir. Yıllık işletme giderinde bakım, sigorta, malike ait aidat ve dönemsel yenileme payı bulunabilir.','Vergi kişiye, istisnaya, gider yöntemine ve güncel tarifeye göre değişir. Araç otomatik vergi tavsiyesi üretmez; kendi durumunuz için hesapladığınız yıllık TL tutarını girin. Vergi sonrası kira kullanıyorsanız vergi alanında aynı tutarı ikinci kez düşmeyin.'],bullets:['Brüt kirayı değil, tahsil edilebilir kirayı kullanın.','En az bir kötümser boşluk senaryosu oluşturun.','Büyük tadilatı yıllık giderle başlangıç maliyetine aynı anda yazmayın.']},
  {title:'Net getiri tek başına yeterli mi?',paragraphs:['Net kira pozitif olsa bile konutun likiditesi, bina riski ve gelecekteki büyük harcamaları farklıdır. Mevduatla karşılaştırmada aynı başlangıç sermayesi, aynı süre ve stopaj sonrası net faiz kullanılmalıdır.','Geri dönüş süresi sabit net kira varsayımıdır. Kira ve giderlerin yıllara göre değişeceği uzun senaryolarda sonucu reel getiri, kira artışı ve farklı doluluk varsayımlarıyla birlikte değerlendirin.']}
 ],faqs:[{q:'Boş kalma süresi neden ekleniyor?',a:'Kiracı değişimi ve pazarlama süresi nedeniyle 12 ayın tamamının tahsil edilememesi riskini gösterir.'},{q:'Aidatı kim ödüyorsa nasıl girmeliyim?',a:'Kiracının ödediği olağan aidatı gider yazmayın. Malike ait ortak gider ve büyük bakım paylarını ekleyin.'},{q:'Net getiri negatif olabilir mi?',a:'Evet. Tahsil edilebilir kira gider ve vergiyi karşılamıyorsa sonuç negatif kalır ve basit geri dönüş süresi hesaplanmaz.'}]},
 'metrekare':{sections:[
  {title:'Metrekare fiyatı nasıl hesaplanır?',paragraphs:['Satış fiyatı seçilen alana bölünür. 5.000.000 TL fiyat ve 100 m² net alan için sonuç 50.000 TL/m² olur. İşlem basittir; asıl risk, ilandaki alan tanımının emsallerle aynı olmamasıdır.','Net alan bağımsız bölüm içinde kullanılabilen alanı ifade eder. Brüt alan duvarları veya ortak alan paylarını içerebilir ve ilanlar arasında standart uygulanmayabilir. Net alanı brüt alanla karşılaştırmak ucuz veya pahalı sonucunu bozabilir.']},
  {title:'Doğru emsal nasıl seçilir?',paragraphs:['Aynı sokak veya mikro bölgede, benzer bina yaşı, kat, cephe, ısınma, asansör, otopark ve hukuki niteliğe sahip ilanları ayırın. İlçe ortalaması tek bir ev için yeterli değildir.','İlan fiyatı gerçekleşmiş satış değildir. Metrekare fiyatını kira çarpanı ve toplam alım maliyetiyle birlikte sınayın; yüksek tadilat ihtiyacı bulunan iki evi yalnız alan üzerinden eşitlemeyin.'],bullets:['Aynı alan türünü kullanın.','Mimari proje ile bağımsız bölümü doğrulayın.','Kapalı balkon veya ortak alanı net alana eklemeyin.','En az üç yakın emsal karşılaştırın.']},
  {title:'Sonucun sınırı',paragraphs:['Araç ekspertiz değeri üretmez. Manzara, kat, bina güvenliği, tapu durumu ve kullanım niteliği fiyatı etkileyebilir. Metrekare sonucu yalnızca karşılaştırmayı standartlaştırır.','Satın alma masrafları metrekare fiyatına dahil değildir. Toplam yatırımın metrekare karşılığını görmek isterseniz alım maliyeti aracındaki toplam tutarı bu sayfadaki fiyat alanına girin.']}
 ],faqs:[{q:'Net mi brüt mü kullanmalıyım?',a:'Karşılaştırdığınız bütün ilanlarda aynı tür alanı kullanın. Kullanılabilirlik için net alan genellikle daha açıklayıcıdır.'},{q:'Balkon ve teras alana dahil mi?',a:'Projeye ve kullanılan tanıma göre değişir. İlan beyanını mimari proje ve yerinde ölçümle doğrulayın.'},{q:'Metrekare fiyatı evin değerini verir mi?',a:'Hayır. Konum, bina, kat, hukuki ve teknik nitelikler ayrıca değerlendirilmelidir.'}]},
 'reel-getiri':{sections:[
  {title:'Nominal ve reel getiri farkı',paragraphs:['Konutun TL fiyatı yükseldiğinde nominal kâr oluşabilir; fakat aynı dönemde enflasyon daha yüksekse satın alma gücü azalabilir. Reel hesap, dönem sonu toplamını enflasyon katsayısına bölerek başlangıç gününün parasıyla karşılaştırır.','Örneğin toplam yatırım 5.200.000 TL, dönem sonu değer ile net kira toplamı 6.500.000 TL ve enflasyon %30 ise reel dönem sonu yaklaşık 5.000.000 TL olur. TL tutarı artmasına rağmen başlangıç satın alma gücüne göre kayıp vardır.']},
  {title:'Hangi nakit akışları kullanılmalı?',paragraphs:['Başlangıç yatırımına satış bedeli ile tapu, komisyon ve ilk tadilat eklenmelidir. Yıllık net kira boşluk, gider ve vergi sonrası tutar olmalıdır. Dönem sonunda satış varsayılıyorsa komisyon ve ilgili satış giderleri ayrıca düşülür.','Konut fiyat değişimi geleceğe yönelik tahmindir. TCMB endeksinin geçmiş yıllık artışını doğrudan gelecek oranı gibi kullanmayın; düşük, temel ve yüksek olmak üzere üç ayrı varsayım çalıştırın.'],bullets:['Aynı başlangıç sermayesini kullanın.','Kira ve değer artışını ayrı gösterin.','Satış giderini yalnız satış varsayımında ekleyin.','Geçmiş performansı garanti olarak sunmayın.']},
  {title:'Sonucu alternatiflerle kıyaslayın',paragraphs:['Reel getiri konutu farklı yıllarla karşılaştırmayı kolaylaştırır; mevduat veya altınla kıyaslamada da aynı dönem kullanılmalıdır. Mevduatta stopaj yalnız faizden düşülmeli, anapara üzerinden hesaplanmamalıdır.','Konutun likiditesi düşük, işlem maliyeti yüksek ve sonucu konuta özgüdür. Yüzde farkı kadar nakit ihtiyacı, kullanım değeri ve risk kapasitesi de kararı etkiler.']}
 ],faqs:[{q:'Reel getiri neden nominal getiriden düşük?',a:'Enflasyon, dönem sonu TL tutarının satın alma gücünü azaltır.'},{q:'Kira reel getiriye dahil mi?',a:'Yıllık net kira alanına girdiğiniz tutar dönem sonu değere eklenir.'},{q:'Geçmiş TÜFE’yi gelecek için kullanabilir miyim?',a:'Yalnızca senaryo olarak kullanabilirsiniz; geçmiş oran geleceğin garantisi değildir.'}]},
 'alim-maliyeti':{sections:[
  {title:'İlan fiyatı toplam maliyet değildir',paragraphs:['Satış fiyatının yanında tapu işlemleri, emlak hizmet bedeli, ekspertiz, krediye bağlı giderler, sigorta, zorunlu tadilat, taşınma ve abonelik masrafları oluşabilir. Araç bu kalemleri TL olarak toplayarak gerçek başlangıç sermayesini gösterir.','Oranlar, tarafların anlaşması ve güncel mevzuata göre değişebilir. Sabit yüzde varsaymak yerine işlem öncesinde alınan güncel teklif veya resmî tahakkuk tutarını girmek daha güvenlidir.']},
  {title:'Masrafı iki kez saymayın',paragraphs:['Kiraya vermeden önce yapılan kalıcı tadilat başlangıç maliyetine eklenebilir. Aynı harcamayı yıllık bakım giderine yeniden yazmak getiriyi iki kez düşürür. Yıllık bakım alanında tekrar eden veya gelecekte beklenen farklı giderler bulunmalıdır.','Kredi anaparası evin bedelinin finansmanıdır; alım masrafı değildir. Faiz, tahsis, ekspertiz ve sigorta gibi finansman maliyetleri ayrı değerlendirilmelidir.'],bullets:['Tapu ve döner sermaye','Emlak hizmet bedeli','Ekspertiz ve kredi yan giderleri','Tadilat ve taşınma','Diğer işlem başlangıç giderleri']},
  {title:'Toplam maliyet neden önemlidir?',paragraphs:['Kira getirisi yalnız ilan fiyatına bölünürse yatırım olduğundan daha kârlı görünür. Net getiri ve alternatif yatırım karşılaştırmasında bu sayfadaki toplam yatırım tutarını başlangıç sermayesi olarak kullanın.','Bütçenin tamamını satış bedeline ayırmak, işlem sonrası nakit açığı doğurabilir. Beklenmeyen masraflar için ayrıca güvenlik payı bırakın; bu pay gerçekleşmiş maliyet olmadığı sürece getiri hesabına gider olarak eklenmemelidir.']}
 ],faqs:[{q:'Tapu harcını otomatik yüzdeyle hesaplıyor musunuz?',a:'Hayır. Güncel yükümlülük ve taraf paylaşımı değişebileceği için kullanıcı doğrulanmış TL tutarını girer.'},{q:'Kredi faizi alım maliyetine eklenir mi?',a:'Toplam finansman kararında dikkate alınır; ancak bu araç başlangıç giderlerini toplar. Faiz için kredi maliyeti aracını kullanın.'},{q:'Tadilat hangi alana yazılmalı?',a:'Alım sonrası zorunlu ilk tadilat başlangıç maliyetine; tekrar eden bakım ise net kira hesabındaki yıllık gidere yazılmalıdır.'}]}
};

export function ToolEditorial({slug}:{slug:string}){const item=copy[slug];if(!item)return null;const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:item.faqs.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))};return <section className="tool-editorial"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>{item.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(text=><p key={text}>{text}</p>)}{section.bullets&&<ul>{section.bullets.map(text=><li key={text}>{text}</li>)}</ul>}</section>)}<section className="tool-faq"><h2>Sık sorulan sorular</h2>{item.faqs.map(f=><details key={f.q}><summary>{f.q}</summary><p>{f.a}</p></details>)}</section><p className="article-updated">Hazırlayan ve kontrol eden: <a href="/yayin-ilkeleri">KonutSeyir Editoryal Ekibi</a> · Son gözden geçirme: 22 Eylül 2026.</p></section>}
