import {Header,Footer} from '../../components/site-chrome';
import {Calculator,Deposit} from '../../components/calculator';
import {FinancialReturns} from '../../components/financial-returns';
import '../financial-returns.css';
export default function Compare(){return <><Header back/><main className="inner compare-page">
 <div className="page-title"><p className="eyebrow">AYNI PARA · AYNI SÜRE · AYNI ENFLASYON</p><h1>Konut, mevduat ve altını aynı sermayeyle karşılaştırın</h1><p>Bir yatırım aracını diğerinden “daha iyi” ilan etmek yerine aynı başlangıç sermayesinin bir yıllık senaryoda nasıl değiştiğini görün. Konutta alım ve satış giderleri ile net kira; mevduatta stopaj; altında ise girdiğiniz fiyat değişimi hesaba katılır.</p></div>
 <section className="decision-guide"><div><b>01</b><h2>Başlangıç sermayesini eşitleyin</h2><p>Konut için satış fiyatına alım masraflarını ekleyin. Karşılaştırmadaki mevduat ve altın aynı toplam sermayeden başlar.</p></div><div><b>02</b><h2>Net nakit akışını kullanın</h2><p>Kira gelirinden boş kalma, işletme gideri ve kendi vergi tutarınızı düşürün. Brüt kira ile mevduatın net faizini karşılaştırmayın.</p></div><div><b>03</b><h2>Reel sonucu ayrıca okuyun</h2><p>Nominal TL artışı tek başına satın alma gücü kazancı değildir. Aynı enflasyon varsayımı üç seçeneğe de uygulanır.</p></div></section>
 <Calculator mode="compare"/>
 <FinancialReturns/>
 <section className="compare-editorial"><h2>Karşılaştırma sonucu nasıl okunmalı?</h2><p>Sonuç kartları geleceği tahmin etmez. Girdiğiniz konut fiyat değişimi, altın değişimi ve mevduat faizi birer senaryodur. Bu nedenle en yararlı kullanım tek bir iyimser oran girmek değil, aynı hesabı düşük, temel ve yüksek varsayımlarla tekrar etmektir. Özellikle konutta işlem maliyeti ve satış süresi, mevduatta vade yenileme oranı, altında ise alış-satış farkı gerçek sonucu değiştirebilir.</p><p>Konutun kira üretmesi ve kullanım değeri bulunması onu yalnız fiyat değişimiyle ölçmeyi eksik bırakır. Buna karşılık mevduat daha likit olsa da bugün görülen yıllık oran sonraki vadelerde aynı kalmayabilir. Altın ise düzenli nakit akışı üretmez ve TL değeri hem ons hem kur hareketinden etkilenebilir. Bu farklılıklar nedeniyle kartlardaki dönem sonu tutarı kararın tamamı değil, ortak bir ölçekte karşılaştırma aracıdır.</p><h2>Mevduat oranı neden otomatik banka teklifi değildir?</h2><p>TCMB tarafından yayımlanan mevduat serisi piyasa istatistiğidir; belirli bir bankanın size vereceği oran değildir. Hesap alanına bankanızdan aldığınız yıllık brüt oranı girmeniz daha doğru sonuç verir. Stopaj oranı da hesabın açılış veya yenileme tarihi ile vadesine göre doğrulanmalıdır.</p></section>
 <div className="standalone-deposit"><div><p className="eyebrow">VADE HESABI</p><h2>Mevduatın tek vade netini ayrıca kontrol edin</h2><p>Üstteki karşılaştırma bir yıllık ortak senaryodur. Bu araç ise bankanızın verdiği brüt oranı belirli gün sayısına uygular ve stopaj sonrası tek vade sonucunu hesaplar. İki aracın aynı işi yaptığı izlenimini böylece ortadan kaldırıyoruz, nihayet insanlık küçük bir zafer kazandı.</p></div><Deposit/></div>
 </main><Footer/></>}
