export const cities=[
 {slug:"istanbul",name:"İstanbul",region:"İstanbul",note:"Yüksek işlem hacmi, geniş ilçe farkları ve kira piyasası nedeniyle tek bir şehir ortalaması karar vermek için yeterli değildir."},
 {slug:"ankara",name:"Ankara",region:"Ankara",note:"Kamu istihdamı, üniversiteler ve yeni gelişim bölgeleri talebi farklı alt pazarlara ayırır."},
 {slug:"izmir",name:"İzmir",region:"İzmir",note:"Merkez, kıyı ve çevre ilçeler arasında kullanım amacı ve sezon etkisi belirgin biçimde değişir."},
 {slug:"adana",name:"Adana",region:"Adana ve Mersin",note:"Kira getirisi ile bina niteliği birlikte incelenmeli; yalnızca metrekare fiyatına göre karar verilmemelidir."},
 {slug:"antalya",name:"Antalya",region:"Antalya, Burdur ve Isparta",note:"Turizm, yabancı talebi ve sezonluk kiralama fiyat ile kira serilerini oynaklaştırabilir."},
 {slug:"bursa",name:"Bursa",region:"Bursa, Eskişehir ve Bilecik",note:"Sanayi koridorları, ulaşım ve yeni konut arzı ilçeler arasında farklı talep yaratır."},
 {slug:"kocaeli",name:"Kocaeli",region:"Kocaeli, Sakarya, Düzce, Bolu ve Yalova",note:"Sanayi istihdamı ve İstanbul bağlantısı güçlüdür; ulaşım süresi analizde ayrıca değerlendirilmelidir."},
 {slug:"konya",name:"Konya",region:"Konya ve Karaman",note:"Geniş şehir yapısı nedeniyle merkez ilçeler ve çevre bölgeler aynı fiyat dinamiğine sahip değildir."},
 {slug:"gaziantep",name:"Gaziantep",region:"Gaziantep, Adıyaman ve Kilis",note:"Nüfus, sanayi ve yeniden yapılaşma göstergeleri satış adediyle birlikte okunmalıdır."},
 {slug:"trabzon",name:"Trabzon",region:"Trabzon, Ordu, Giresun, Rize, Artvin ve Gümüşhane",note:"Topoğrafya, ulaşım ve yabancı talebi mikro konum farklarını büyütebilir."},
] as const;

export const guides=[
 {slug:"kira-carpani-nedir",title:"Kira çarpanı nedir?",summary:"Bir evin fiyatının yıllık kiraya oranını doğru yorumlama yöntemi.",body:["Kira çarpanı, satış fiyatının yıllık brüt kiraya bölünmesiyle bulunur. 5.000.000 TL değerindeki bir ev ayda 30.000 TL kira getiriyorsa yıllık kira 360.000 TL, kira çarpanı yaklaşık 13,9 yıldır.","Bu sonuç tek başına ucuzluk göstergesi değildir. Boş kalma süresi, bakım, aidat, vergi, sigorta ve satın alma masrafları net getiriyi düşürür. Aynı zamanda binanın yaşı ve bölgede beklenen arz da gelecekteki kirayı etkiler.","Karşılaştırmayı aynı semtte, benzer bina yaşı ve benzer kullanım niteliğine sahip evlerle yapın. Brüt ve net kira çarpanlarını ayrı gösterin."]},
 {slug:"ev-pahali-mi",title:"Bir evin pahalı olduğu nasıl anlaşılır?",summary:"İlan fiyatını tek bir ortalamaya değil, birden fazla ölçüte göre test edin.",body:["Önce ilandaki net ve brüt alanın hangisinin kullanıldığını belirleyin. Satış fiyatını karşılaştırırken aynı alan tanımını kullanmayan iki ilan yanıltıcı sonuç verir.","Metrekare fiyatına ek olarak kira çarpanı, bina yaşı, kat, cephe, otopark, deprem incelemesi ve hukuki durum değerlendirilmelidir. Bölgesel endeks yalnızca genel eğilimi gösterir; tek bir dairenin değerini belirlemez.","En doğru soru 'Bu ev kaç lira eder?' değil, 'Bu fiyat hangi varsayımlar gerçekleşirse mantıklı olur?' sorusudur."]},
 {slug:"net-kira-getirisi",title:"Net kira getirisi nasıl hesaplanır?",summary:"Brüt kira yerine elde kalan gerçek nakit akışını hesaplayın.",body:["Net yıllık kira; tahsil edilen kiradan boş kalma, bakım, malikçe ödenen aidat, sigorta ve vergiler çıkarılarak hesaplanır. Net getiri oranında payda yalnızca ev fiyatı değil, tapu ve tadilat gibi başlangıç maliyetlerini de içermelidir.","Bir aylık boş kalma olasılığını sıfır kabul etmek sonucu gereğinden iyi gösterir. Eski binalarda bakım payı için ayrıca senaryo oluşturmak gerekir.","Vergi kişiye ve döneme göre değişebildiği için sabit oran kullanmak yerine kullanıcıya düzenlenebilir gider alanı sunulmalıdır."]},
 {slug:"reel-konut-getirisi",title:"Reel konut getirisi neden önemlidir?",summary:"TL fiyat artışı ile satın alma gücü artışını birbirinden ayırın.",body:["Konut fiyatı yüzde 40 artarken tüketici enflasyonu yüzde 50 ise yatırım nominal olarak yükselmiş, reel olarak gerilemiştir. Reel değişim basitçe 40-50 değildir; (1,40 / 1,50)-1 formülüyle yaklaşık eksi yüzde 6,7 bulunur.","Kira dahil toplam getiri hesaplanırken kira nakit akışı ayrıca eklenir. Geçmiş endeks performansı geleceğe ilişkin garanti değildir.","Reel getiri, farklı yılları ve yatırım türlerini ortak satın alma gücü ölçüsünde karşılaştırmayı sağlar."]},
 {slug:"ev-mi-mevduat-mi",title:"Ev mi mevduat mı?",summary:"Nakit akışı, likidite ve risk farklarını aynı vadede karşılaştırın.",body:["Mevduatın getirisi belirli vadede daha görünürdür; konutun getirisi ise kira, değer değişimi ve satış maliyetinin birleşimidir. Bu nedenle yalnızca yıllık faiz ile konut fiyat artışını karşılaştırmak eksik kalır.","Konut için tapu, komisyon, tadilat, boş kalma ve satış süresi; mevduat için stopaj ve vade yenileme riski hesaba katılmalıdır.","Karşılaştırma aynı başlangıç parası ve aynı dönem üzerinden yapılmalıdır. Kredi kullanılıyorsa özkaynak getirisi ayrıca hesaplanmalıdır."]},
 {slug:"konut-kredisi-maliyeti",title:"Konut kredisi gerçek maliyeti",summary:"Aylık faiz oranının toplam geri ödemeye etkisini görün.",body:["Eşit taksitli kredide faiz her ay kalan anapara üzerinden işler. Küçük görünen aylık oran, uzun vadede toplam geri ödemeyi ciddi biçimde büyütebilir.","Tahsis ücreti, ekspertiz, sigorta ve ipotek masrafları yalnızca faiz formülünde görünmez. Bankanın yıllık maliyet oranı ve ödeme planı birlikte incelenmelidir.","Vade uzadığında taksit düşebilir fakat toplam finansman maliyeti çoğunlukla artar. Farklı vadeleri aynı kredi tutarıyla karşılaştırın."]},
 {slug:"tapu-kontrolu",title:"Tapu kaydında neler kontrol edilmeli?",summary:"Malik, nitelik, pay ve kısıtlamaları ödeme öncesinde doğrulayın.",body:["Tapu belgesindeki bağımsız bölüm, arsa payı, nitelik ve malik bilgileri fiilî durumla eşleşmelidir. Kat irtifakı ile kat mülkiyeti aynı hukuki durumu ifade etmez.","İpotek, haciz, şerh ve beyanlar yetkili kanaldan kontrol edilmelidir. Ekran görüntüsü veya satıcının sözlü beyanı resmî kayıt yerine geçmez.","Belirsizlik varsa sözleşme ve ödeme öncesinde tapu müdürlüğü ile alanında uzman hukukçudan destek alınmalıdır."]},
 {slug:"iskan-kat-mulkiyeti",title:"İskân ve kat mülkiyeti farkı",summary:"Binanın kullanım izni ile bağımsız bölüm mülkiyetini ayırın.",body:["Yapı kullanma izin belgesi, yapının ruhsat ve eklerine uygun tamamlandığına ilişkin idari belgedir. Kat mülkiyeti ise bağımsız bölümler üzerindeki mülkiyet düzenidir.","Bir ilanda bu kavramlardan birinin yazması diğerinin otomatik olarak bulunduğu anlamına gelmez. Belediye ve tapu kayıtları ayrı ayrı doğrulanmalıdır.","Krediye uygunluk da tek başına bütün hukuki ve teknik risklerin giderildiğini göstermez."]},
 {slug:"deprem-riski-kontrolu",title:"Deprem riski nasıl araştırılır?",summary:"Bölgesel tehlike ile bina performansını birbirine karıştırmayın.",body:["AFAD haritası bölgesel yer hareketi tehlikesini gösterir; belirli bir binanın sağlamlığını ölçmez. Zemin, taşıyıcı sistem, proje, malzeme ve sonradan yapılan değişiklikler ayrıca değerlendirilir.","Bina yaşı tek başına güvenlik kararı verdirmez. Ruhsat ve proje kayıtları incelenmeli, gerekli durumda yetkili kuruluşlardan teknik inceleme alınmalıdır.","'Düşük riskli ilçe' gibi genel ifadeler tek bir yapı için güvence değildir."]},
 {slug:"aidat-borc-kontrolu",title:"Aidat ve ortak gider kontrolü",summary:"Dairenin düzenli maliyetlerini satın almadan önce görün.",body:["Yüksek aidat net kira getirisini düşürür ve yeniden satış talebini etkileyebilir. Yönetim planı, son dönem bütçesi ve planlanan büyük onarımlar incelenmelidir.","Geçmiş borçların kime ait olduğu ve devir tarihinde nasıl kapatılacağı sözleşmede açık olmalıdır. Site yönetiminden yazılı borç durumu alınması yararlıdır.","Asansör, çatı, cephe ve güçlendirme gibi yaklaşan harcamalar olağan aidattan ayrı değerlendirilmelidir."]},
 {slug:"kiracili-ev-almak",title:"Kiracılı ev alırken dikkat",summary:"Kira sözleşmesi ve tahliye varsayımını satın alma kararına katın.",body:["Mülkiyetin devri mevcut kira ilişkisini kendiliğinden sona erdirmez. Kira sözleşmesi, depozito, ödeme düzeni ve kullanım durumu incelenmelidir.","Evi kısa sürede boş teslim alma varsayımı hukuki dayanak olmadan fiyatlamaya eklenmemelidir. Tahliye süreçleri koşula göre değişir.","Satın alma amacı oturum ise teslim tarihi; yatırım ise mevcut kira ile piyasa kirası arasındaki fark ayrıca değerlendirilmelidir."]},
 {slug:"brut-net-metrekare",title:"Brüt ve net metrekare",summary:"İlan karşılaştırmalarındaki en yaygın ölçüm hatasını önleyin.",body:["Net alan, bağımsız bölüm içinde kullanılabilen alanı; brüt alan ise tanıma göre duvarları veya ortak alan paylarını içerebilir. İlanlarda kullanılan brüt tanımı standart olmayabilir.","Aynı fiyatlı iki evin ilandaki metrekareleri farklı yöntemle yazılmışsa metrekare fiyatı karşılaştırması yanlış çıkar.","Mimari proje, tapu bilgisi ve yerinde ölçüm arasında tutarlılık arayın; hesaplayıcıya hangi alanı girdiğinizi not edin."]},
 {slug:"ilan-fiyati-pazarlik",title:"İlan fiyatı ve pazarlık payı",summary:"İlan fiyatını gerçekleşmiş satış fiyatı gibi kullanmayın.",body:["İlan fiyatı satıcının talebidir; gerçekleşen tapu bedelini göstermez. Uzun süredir yayında olan veya sık fiyat değiştiren ilanlar piyasa değerine ilişkin tek başına kanıt değildir.","Benzer ilanları bina yaşı, sokak, kat, cephe ve hukuki durum bakımından daraltın. Pazarlık hedefini yalnızca yüzdesel alışkanlığa göre belirlemeyin.","Ekspertiz, kira getirisi ve alternatif yatırım maliyeti teklif sınırını belirlemede birlikte kullanılabilir."]},
 {slug:"emlak-alim-masraflari",title:"Ev alırken unutulan masraflar",summary:"Satış fiyatının dışındaki başlangıç maliyetlerini bütçeye ekleyin.",body:["Tapu harcı, döner sermaye, emlak hizmet bedeli, ekspertiz, kredi masrafları, sigorta, abonelik ve tadilat toplam yatırım maliyetini artırır.","Oran ve uygulamalar değişebildiği için işlem gününde resmî kaynak ve hizmet sağlayıcıdan doğrulama yapılmalıdır.","Getiri hesabında bu tutarları başlangıç maliyetine eklememek, yatırımın olduğundan daha kârlı görünmesine yol açar."]},
 {slug:"konut-endeksi-okuma",title:"Konut fiyat endeksi nasıl okunur?",summary:"Endeks değişimini tek bir evin ekspertiz değeri sanmayın.",body:["Konut Fiyat Endeksi, belirli bölgedeki genel fiyat hareketini zaman içinde izler. Endeksin yüzde 30 artması, bölgedeki her evin aynı oranda arttığı anlamına gelmez.","Nitelik, konum ve dönem farklılıkları mikro ölçekte büyük sapmalar yaratabilir. Endeks yön ve bağlam sağlar; ilan değerlemesinin yerini tutmaz.","Nominal endeks ile TÜFE'ye göre reel endeks ayrı izlenmelidir."]},
] as const;

export type GuideSection={heading:string;paragraphs:string[];bullets?:string[]};

export const guideExpansions:Record<string,GuideSection[]>={
 "kira-carpani-nedir":[
  {heading:"Kira çarpanı nasıl hesaplanır?",paragraphs:["Kira çarpanı, konut için ödenen toplam başlangıç tutarının bir yıllık kira gelirine bölünmesidir. Satış bedeli 5.000.000 TL, aylık kira 30.000 TL ise yıllık brüt kira 360.000 TL olur. Yalnızca satış bedeli kullanıldığında brüt kira çarpanı 13,9 yıl çıkar.","Hesabı ay cinsinden görmek için satış fiyatını aylık kiraya bölebilirsiniz. Aynı örnekte sonuç yaklaşık 167 aydır. Bu sayı, kira hiç değişmez ve konut hiç boş kalmazsa satış bedelinin brüt kirayla kaç ayda karşılanacağını anlatır; yatırımın gerçekten o tarihte kendini ödediğini garanti etmez."],bullets:["Brüt yıllık kira = aylık kira × 12","Brüt getiri = yıllık kira ÷ satış fiyatı × 100","Kira çarpanı = satış fiyatı ÷ yıllık kira"]},
  {heading:"Net kira çarpanı neden daha uzundur?",paragraphs:["Tapu gideri, emlak hizmet bedeli ve başlangıç tadilatı yatırımın ilk günkü maliyetini artırır. Boş kalma, malik tarafından ödenen aidat, bakım, sigorta ve vergi ise her yıl elde kalan kirayı azaltır. Bu nedenle net hesapta pay büyür, yıllık gelir küçülür ve geri dönüş süresi uzar.","Örneğin toplam başlangıç maliyeti 5.250.000 TL ve giderlerden sonra yıllık net kira 300.000 TL ise net kira çarpanı 17,5 yıldır. Brüt 13,9 yıl ile net 17,5 yıl arasındaki fark, yalnızca küçük giderlerin değil satın alma maliyetlerinin de karar üzerindeki etkisini gösterir."]},
  {heading:"Kaç yıllık çarpan iyidir?",paragraphs:["Her şehir ve mahalle için geçerli tek bir iyi çarpan yoktur. Yeni bina, güçlü ulaşım bağlantısı veya sınırlı arz daha yüksek çarpanla işlem görebilir. Bakım ihtiyacı yüksek, kiracı talebi zayıf ya da hukuki belirsizliği bulunan konutta düşük çarpan tek başına fırsat anlamına gelmez.","Aynı tarihte, aynı bölgede, benzer bina yaşı ve kullanım niteliğindeki konutları karşılaştırın. Bir ilanın çarpanını şehir ortalamasıyla karşılaştırmak yerine mümkünse aynı sokak veya yakın çevredeki gerçekçi kiralarla test edin. İlan kirasını değil, sürdürülebilir tahsil edilebilir kirayı kullanın."]},
  {heading:"Karar verirken kontrol listesi",paragraphs:["Kira çarpanını ilk eleme aracı olarak kullanın; nihai değerleme olarak kullanmayın. Konutun satış süresi, gelecekteki büyük bakım giderleri, deprem ve zemin incelemesi, tapu durumu ve alternatif yatırım getirisi ayrıca değerlendirilmelidir."],bullets:["Aylık kira emsalini en az üç benzer ilanla doğrulayın.","Bir aylık boşluk ve olağan bakım için ayrı senaryo kurun.","Brüt ve net çarpanı yan yana görün.","Mevduatın stopaj sonrası net getirisiyle aynı süre üzerinden karşılaştırın."]}
 ],
 "ev-pahali-mi":[
  {heading:"Önce karşılaştırılabilir konutu tanımlayın",paragraphs:["Bir evin pahalı olup olmadığını anlamanın ilk adımı, gerçekten benzer konutları ayırmaktır. Aynı ilçedeki iki daire; sokak, bina yaşı, kat, cephe, asansör, otopark, manzara, ısınma sistemi ve tapu niteliği nedeniyle farklı fiyatlanabilir.","Net alanı brüt alanla karşılaştırmak en yaygın hatadır. İlanlarda brüt metrekare tanımı standart uygulanmayabilir. Metrekare fiyatını hesaplarken aynı alan türünü kullandığınızdan emin olun ve mümkünse mimari proje ile yerinde ölçümü doğrulayın."],bullets:["Aynı mikro bölge","Benzer bina yaşı","Aynı net/brüt alan tanımı","Benzer kat, cephe ve donanım","Benzer hukuki durum"]},
  {heading:"Fiyatı üç ayrı ölçüyle sınayın",paragraphs:["Birinci ölçü emsal metrekare fiyatıdır. İkinci ölçü, gerçekçi kira üzerinden bulunan net kira getirisi ve kira çarpanıdır. Üçüncü ölçü ise aynı sermayenin mevduat veya başka düşük riskli araçta sağlayabileceği net getiridir.","Üç ölçü de aynı yöne işaret ediyorsa karar daha güçlüdür. Metrekare fiyatı makul görünürken kira getirisi çok düşükse fiyat, yatırımcıdan çok oturum amaçlı talebi yansıtıyor olabilir. Kira getirisi yüksek görünen bir ilanda ise olağan dışı gider veya tahliye riski bulunabilir."]},
  {heading:"Endeks ve ilan fiyatının sınırı",paragraphs:["TCMB Konut Fiyat Endeksi bölgesel eğilimi gösterir; tek bir dairenin ekspertiz değeri değildir. Endeks yükselirken belirli bir binanın yaşı, bakım ihtiyacı veya çevresindeki arz nedeniyle aynı ölçüde değer kazanmaması mümkündür.","İlan fiyatı gerçekleşmiş satış fiyatı değildir. Uzun süre yayında kalan ilanlar veya sık değiştirilen fiyatlar piyasanın kabul ettiği değeri göstermeyebilir. Teklifinizi ilan sahibinin istediği indirim yüzdesine göre değil, toplam maliyet ve beklenen nakit akışına göre sınırlandırın."]},
  {heading:"Makul fiyat aralığı oluşturun",paragraphs:["Tek bir kesin değer yerine düşük, orta ve yüksek olmak üzere üç senaryo oluşturun. Kötümser senaryoda daha düşük kira, bir aylık boşluk ve ek tadilat; temel senaryoda doğrulanmış emsal; iyimser senaryoda ise ulaşılabilir fakat garanti olmayan değer artışı kullanın."],bullets:["Tapu ve başlangıç giderlerini fiyata ekleyin.","Beklenen tadilat için yazılı teklif alın.","Kredi kullanıyorsanız toplam finansman maliyetini dahil edin.","Ekspertiz, hukuki kontrol ve teknik incelemeyi pazarlıktan önce tamamlayın."]}
 ],
 "net-kira-getirisi":[
  {heading:"Brüt gelirden net nakit akışına",paragraphs:["Brüt kira, aylık sözleşme bedelinin 12 ile çarpılmasıdır. Net kira geliri ise yıl içinde gerçekten tahsil edilmesi beklenen tutardan konuta bağlı giderlerin çıkarılmasıyla bulunur. Yatırım kararı için esas alınması gereken sayı net nakit akışıdır.","Aylık 30.000 TL kiralı bir konutun brüt yıllık geliri 360.000 TL'dir. Bir ay boş kalma, 20.000 TL bakım ve sigorta ile 15.000 TL malik gideri varsayılırsa vergi öncesi net tutar 295.000 TL'ye iner. Vergi etkisi kişinin durumuna göre ayrıca hesaplanmalıdır."],bullets:["Tahsil edilen kira","Boş kalma kaybı","Bakım ve yenileme","Malike ait aidat ve ortak gider","Sigorta ve vergiler"]},
  {heading:"Doğru paydayı kullanın",paragraphs:["Net getiri oranında yalnızca ilan fiyatını kullanmak sonucu iyimser gösterir. Tapu gideri, emlak hizmet bedeli, ekspertiz, krediye bağlı masraflar ve kiraya vermek için yapılan tadilat toplam başlangıç yatırımına eklenmelidir.","Örneğin ev 5.000.000 TL olsa bile toplam yatırım 5.300.000 TL'ye çıkabilir. Yıllık net kira 295.000 TL ise net getiri yüzde 5,57 olur. Yalnızca satış fiyatına bölündüğünde görülen yüzde 5,90 aynı yatırımın daha yüksek getirili olduğu izlenimini verir."]},
  {heading:"Vergiyi iki kez düşmeyin",paragraphs:["Kira gelir vergisi sabit bir gider değildir; istisna, gider yöntemi, diğer gelirler ve güncel tarifeye göre değişir. Hesaplayıcıya vergi sonrası net kira giriyorsanız ayrıca vergi gideri eklemeyin. Brüt kira giriyorsanız tahmini vergiyi tek kez düşürün.","Aynı yaklaşım aidat için de geçerlidir. Kiracının ödediği olağan aidatı malik giderine yeniden yazmak, getiriyi gereksiz yere düşürür. Büyük onarım, demirbaş ve malike kalan ortak giderler ise ayrı tutulmalıdır."]},
  {heading:"Üç senaryoyla ölçün",paragraphs:["Tek bir yılın sonucuna güvenmek yerine doluluk ve gider varsayımlarını değiştirin. Kötümser senaryo, nakit akışının ne kadar dayanıklı olduğunu gösterir; iyimser senaryo ise kararın yalnızca yüksek kira artışına bağlı olup olmadığını ortaya çıkarır."],bullets:["Temel: 11 ay tahsilat ve olağan bakım","Kötümser: 10 ay tahsilat ve yüksek bakım","İyimser: 12 ay tahsilat; yine de sıfır gider değil","Her senaryoyu stopaj sonrası mevduatla aynı sermaye üzerinden karşılaştırın."]}
 ],
 "reel-konut-getirisi":[
  {heading:"Nominal artış kazanç anlamına gelmeyebilir",paragraphs:["Konutun TL fiyatındaki artış nominal getiridir. Aynı dönemde genel fiyat düzeyi daha hızlı yükselmişse konutun satın alma gücü azalabilir. Bu nedenle yüzde 40 konut artışından yüzde 50 enflasyonu doğrudan çıkarmak yerine bileşik reel getiri formülü kullanılmalıdır.","Formül (1 + nominal getiri) ÷ (1 + enflasyon) − 1 şeklindedir. Yüzde 40 nominal artış ve yüzde 50 enflasyonda sonuç yaklaşık yüzde eksi 6,7'dir. Konut TL olarak değer kazanmış görünürken reel olarak kayıp oluşmuştur."]},
  {heading:"Kira dahil toplam getiriyi kurun",paragraphs:["Yalnızca satış fiyatındaki değişimi kullanmak, kiraya verilen konutun toplam performansını eksik gösterir. Dönem içindeki net kira nakit akışı değer değişimine eklenmeli; başlangıç tapu ve tadilat giderleri ile satış maliyetleri düşülmelidir.","Kira farklı aylarda tahsil edildiği için ileri düzey karşılaştırmada nakit akışlarının zamanı da önemlidir. Basit yıllık hesap karar desteği sağlar; fakat uzun dönemli projeksiyonda kira artışı, boşluk, vergi ve yeniden yatırım varsayımları açıkça yazılmalıdır."]},
  {heading:"Doğru enflasyon dönemini eşleştirin",paragraphs:["Ocak ayındaki alış ile aralık ayındaki değeri karşılaştırırken aynı tarih aralığının TÜFE değişimi kullanılmalıdır. Yıllık manşet oranı farklı tarihlere uygulamak dönem uyumsuzluğu yaratır. Aylık endeks değerleri başlangıç ve bitiş ayına göre eşleştirilmelidir.","TÜFE kişisel harcama sepetinizi birebir temsil etmeyebilir; buna rağmen farklı yıllardaki TL tutarlarını ortak bir satın alma gücü ölçüsünde karşılaştırmak için resmî ve tekrarlanabilir referanstır."]},
  {heading:"Sonucu nasıl yorumlamalı?",paragraphs:["Pozitif reel getiri, konutun incelenen dönemde genel enflasyonun üzerinde performans gösterdiğini söyler; gelecekte de aynı sonucu vereceğini söylemez. Negatif reel getiri de konutun kullanım değeri veya kira geliri yokmuş gibi yorumlanmamalıdır."],bullets:["Nominal değer artışını ayrı gösterin.","Net kira gelirini ayrıca ekleyin.","Başlangıç ve satış maliyetlerini düşürün.","Aynı dönemin TÜFE endeksini kullanın.","Geçmiş sonucu gelecek tahmini olarak sunmayın."]}
 ],
 "ev-mi-mevduat-mi":[
  {heading:"Aynı sermaye ve aynı süre kuralı",paragraphs:["Karşılaştırmanın adil olması için iki seçenekte de aynı başlangıç parası ve aynı yatırım dönemi kullanılmalıdır. Konutta peşinatı, tapu ve tadilat giderlerini; mevduatta ise yatırılan anaparayı başlangıç sermayesi olarak kaydedin.","Konut krediyle alınıyorsa yalnızca ev fiyatını mevduatla karşılaştırmak doğru değildir. Özkaynak, kredi taksitleri, faiz ve ek masraflar ayrı nakit akışlarıdır. Kredili senaryo, peşin alım senaryosundan ayrı değerlendirilmelidir."]},
  {heading:"Mevduatın net sonucunu bulun",paragraphs:["Banka oranı yıllık brüt orandır. Vade getirisi gün sayısına göre hesaplanır ve stopaj yalnızca faiz üzerinden kesilir. Vade sonunda aynı oranın tekrar bulunacağı garanti olmadığı için bir yıllık karşılaştırmada yenileme oranı varsayımı açık olmalıdır.","Mevduatın güçlü tarafı likidite ve öngörülebilir kısa vadeli nakit akışıdır. Zayıf tarafı ise faiz düşüşünde yenileme getirisinin azalması ve yüksek enflasyon döneminde reel satın alma gücünün korunamamasıdır."]},
  {heading:"Konutun bütün nakit akışını ekleyin",paragraphs:["Konut getirisi; net kira, değer değişimi ve satışta oluşan maliyetlerin toplamıdır. Boş kalma, bakım, aidat, vergi, sigorta ve tahsilat riski hesaba katılmadan yapılan karşılaştırma konutu olduğundan kârlı gösterir.","Konutun likiditesi mevduattan düşüktür. Satışın aylar sürmesi, pazarlık indirimi ve işlem gideri beklenen getirinin nakde dönüşmesini geciktirebilir. Buna karşılık konut kullanım hakkı ve uzun vadeli kira potansiyeli sunar."]},
  {heading:"Sonuç bir sıralamadan fazlasıdır",paragraphs:["Bir yıllık beklenen TL kazancı en yüksek seçenek her kullanıcı için en doğru seçenek olmayabilir. Acil nakit ihtiyacı, borç kapasitesi, tek varlıkta yoğunlaşma ve yönetim yükü kararın parçasıdır."],bullets:["Net TL kazancı ve reel getiriyi birlikte görün.","Kötümser konut senaryosunu hesaba katın.","Mevduat yenileme faizini sabit varsaymayın.","Likidite ihtiyacını ve satış süresini değerlendirin.","Geçmiş endeks artışını garanti getiri kabul etmeyin."]}
 ],
 "konut-kredisi-maliyeti":[
  {heading:"Aylık oran neden yanıltıcı olabilir?",paragraphs:["Konut kredileri genellikle aylık faiz oranıyla ifade edilir. Aylık yüzde 2,5 oranı yıllık yüzde 30 ile aynı maliyet değildir; bileşik etki ve masraflar toplam maliyeti yükseltir. Karşılaştırmada bankanın yıllık maliyet oranı ve ödeme planı birlikte incelenmelidir.","Eşit taksitli kredide her taksitin bir bölümü faiz, bir bölümü anaparadır. İlk aylarda faiz payı daha yüksek olabilir. Toplam faiz, aylık taksit ile vade çarpımından kredi anaparasının çıkarılmasıyla kabaca görülebilir; sigorta ve ücretler ayrıca eklenir."]},
  {heading:"Masrafları kredi dışında bırakmayın",paragraphs:["Tahsis ücreti, ekspertiz, ipotek tesis gideri, zorunlu sigortalar ve hesapla bağlantılı maliyetler yalnızca faiz formülünde görünmez. Bazı kalemler başlangıçta peşin, bazıları her yıl tahsil edilir.","Bankalardan teklif alırken yalnızca aylık taksiti değil toplam geri ödeme, yıllık maliyet oranı, erken ödeme koşulları ve sigorta yenileme tutarlarını aynı tabloda isteyin. Düşük taksit, uzun vade nedeniyle daha yüksek toplam maliyet yaratabilir."]},
  {heading:"Vade ve peşinat senaryosu",paragraphs:["Vade uzadıkça aylık ödeme genellikle düşer; fakat borcun faize maruz kaldığı süre uzar. Daha yüksek peşinat toplam faizi azaltabilir, ancak bütün nakdi eve bağlamak acil durum rezervini ortadan kaldırabilir.","En az üç senaryo kurun: yüksek peşinat-kısa vade, dengeli peşinat-orta vade ve düşük peşinat-uzun vade. Her senaryoda aylık ödeme kapasitesini ve toplam maliyeti birlikte değerlendirin."]},
  {heading:"Stres testi yapın",paragraphs:["Kredi taksiti bugün ödenebilir görünse bile gelir azalması, aidat artışı veya beklenmeyen bakım gideri bütçeyi zorlayabilir. Taksit sonrası kalan nakit, temel giderler ve acil durum rezervi için yeterli olmalıdır."],bullets:["En az birkaç aylık ödeme rezervi bırakın.","Değişebilecek sigorta ve yan giderleri ekleyin.","Ara ödeme ve erken kapama koşullarını okuyun.","Kira gelirine güveniliyorsa boş kalma senaryosu uygulayın."]}
 ],
 "tapu-kontrolu":[
  {heading:"Taşınmazın kimliğini doğrulayın",paragraphs:["Tapudaki il, ilçe, mahalle, ada, parsel, blok, bağımsız bölüm ve nitelik bilgileri satın alınan yerle birebir eşleşmelidir. Daire numarası ile tapudaki bağımsız bölüm numarasının farklı olabileceğini unutmayın; mimari proje üzerinden doğrulama yapın.","Malik bilgisi ve satış yetkisi kontrol edilmeden kapora veya ödeme yapılmamalıdır. Vekâletle satışta belgenin kapsamı, geçerliliği ve ilgili taşınmaz için satış yetkisi resmî kanaldan incelenmelidir."]},
  {heading:"Şerh, beyan ve takyidatlar",paragraphs:["İpotek, haciz, intifa, aile konutu şerhi, satış vaadi ve diğer kısıtlamalar mülkiyet devrini veya kullanım hakkını etkileyebilir. Tapu kaydının yalnızca ön yüzü yeterli değildir; güncel takyidat bilgisi yetkili kanal üzerinden alınmalıdır.","Bir kaydın satış sırasında kaldırılacağı söyleniyorsa işlem sırası, ödeme yöntemi ve terkin koşulu yazılı biçimde planlanmalıdır. Sözlü taahhüt, resmî terkin işleminin yerine geçmez."]},
  {heading:"Kat mülkiyeti ve arsa payı",paragraphs:["Kat irtifakı, kat mülkiyeti ve arsa tapusu farklı hukuki durumları ifade eder. Fiilen konut olarak kullanılan bir yerin tapu niteliği depo veya iş yeri olabilir. Bu fark kredi, kullanım, vergi ve yeniden satış süreçlerini etkileyebilir.","Arsa payının projedeki bağımsız bölümle uyumu ve ortak alan düzeni incelenmelidir. Özellikle dönüşüm ihtimali bulunan yapılarda arsa payı ilerideki hak dağılımı açısından önem taşıyabilir."]},
  {heading:"Ödeme öncesi dosya",paragraphs:["Tapu kontrolü tek başına teknik güvenlik veya imar uygunluğu sağlamaz. Belediye ruhsatı, iskân, proje, yönetim planı ve bina incelemesi ayrı başlıklardır."],bullets:["Güncel tapu kaydı ve takyidat","Kimlik ve satış yetkisi","Bağımsız bölüm-proje eşleşmesi","Kat mülkiyeti veya irtifak durumu","Arsa payı ve yönetim planı","Gerekirse gayrimenkul hukukçusu incelemesi"]}
 ],
 "iskan-kat-mulkiyeti":[
  {heading:"İskân neyi gösterir?",paragraphs:["Yapı kullanma izin belgesi, yapının ruhsat ve onaylı projelerine uygun tamamlandığına ilişkin idari belgedir. Belge bina veya ilgili bölüm için düzenlenir; yapının deprem performansını ya da bütün sonradan yapılan değişikliklerin uygunluğunu tek başına garanti etmez.","İskân bulunmaması abonelik, kredi, kat mülkiyetine geçiş ve yeniden satış süreçlerinde sorun yaratabilir. Neden alınmadığı, tamamlanmamış yükümlülük ve güncel belediye kayıtları incelenmelidir."]},
  {heading:"Kat irtifakı ile kat mülkiyeti",paragraphs:["Kat irtifakı, yapılacak veya yapılmakta olan yapıda bağımsız bölümlere bağlanan arsa payı esaslı haktır. Kat mülkiyeti ise tamamlanmış yapıdaki bağımsız bölüm mülkiyetidir. Bir ilanda kat irtifakı yazması iskânın bulunduğunu göstermez.","Kat mülkiyetine geçilmiş olması da dairenin mevcut kullanımının projeye tamamen uygun olduğunu kanıtlamaz. Balkon kapatma, bölüm birleştirme veya ortak alan kullanımı gibi sonradan değişiklikler ayrıca araştırılmalıdır."]},
  {heading:"Belgeler nasıl doğrulanır?",paragraphs:["Satıcıdan alınan fotoğraf veya ilan açıklaması yerine tapu ve belediye kayıtlarını kullanın. Bağımsız bölüm numarası, onaylı mimari projedeki konum ve fiilî daire birlikte kontrol edilmelidir.","Krediye uygunluk olumlu bir işaret olabilir; fakat bankanın ekspertizi alıcının bütün hukuki ve teknik inceleme yükümlülüğünü üstlenmez. Ekspertiz raporundaki şerh ve uyumsuzluk notlarını okuyun."]},
  {heading:"Satın alma öncesi sorular",paragraphs:["Belirsizlik varsa kapora sözleşmesine belge doğrulama ve iade koşulları açıkça yazılmalıdır. İskân sorununun daha sonra kolayca çözüleceği varsayımı maliyet ve süre araştırılmadan kabul edilmemelidir."],bullets:["Yapı ruhsatı ve kullanım izni mevcut mu?","Tapu niteliği fiilî kullanımla uyumlu mu?","Bağımsız bölüm onaylı projede doğru yerde mi?","Ortak alan veya projeye aykırı değişiklik var mı?","Kat mülkiyetine geçiş için borç ya da eksik işlem bulunuyor mu?"]}
 ]
};

export const cityEvaluations:Record<string,{title:string;paragraphs:string[];checks:string[]}>= {
 istanbul:{title:"İstanbul için değerlendirme",paragraphs:["İstanbul tek bir konut piyasası değildir. Aynı ilçede dahi raylı sisteme yürüme mesafesi, yapı yaşı, zemin koşulları ve iş merkezlerine ulaşım süresi fiyat ile kirayı farklılaştırır. İl geneli endeks yön gösterir; teklif fiyatını doğrulamaz.","Yatırım hesabında yüksek satış fiyatının yanında kiracı devir hızı, bina bakım bütçesi ve olası dönüşüm süreci ayrıca incelenmelidir. Avrupa ve Anadolu yakası ortalamalarını birbirinin emsali kabul etmek yerine mikro bölge bazında veri toplayın."],checks:["Ulaşım süresi ve planlanan hatlar","Bina/zemin incelemesi ve dönüşüm durumu","Aynı sokakta net kira emsalleri"]},
 ankara:{title:"Ankara için değerlendirme",paragraphs:["Ankara’da kamu kurumları, üniversiteler, savunma sanayii ve yeni gelişim aksları farklı kiracı profilleri oluşturur. Çankaya’daki olgun mahallelerle çevre ilçelerdeki yeni projelerin fiyatlama mantığı aynı değildir.","Metro erişimi, kampüs ve iş alanlarına ulaşım, ısınma gideri ve site aidatı net getiriyi belirgin etkiler. Yeni projelerde ilan fiyatı yanında tamamlanmış çevre altyapısı ve boş konut arzı da kontrol edilmelidir."],checks:["İş ve üniversite merkezlerine erişim","Isınma tipi ve yıllık ortak gider","Yeni proje arzı ve doluluk"]},
 izmir:{title:"İzmir için değerlendirme",paragraphs:["İzmir’de merkez, kuzey-güney gelişim aksları ve kıyı ilçeleri farklı kullanım amaçlarına sahiptir. Sürekli oturum talebi ile yazlık veya sezonluk talebi aynı kira varsayımıyla değerlendirmek hatalıdır.","Kıyıya yakınlık prim yaratabilir; ancak yapı yaşı, nem ve bakım ihtiyacı toplam maliyeti artırabilir. Ulaşım bağlantısı, deprem ve zemin incelemesi ile yıl boyu kiralanabilirlik birlikte ele alınmalıdır."],checks:["Sürekli ve sezonluk talep ayrımı","Yapı yaşı, nem ve bakım bütçesi","Raylı sistem ve ana ulaşım erişimi"]},
 adana:{title:"Adana için değerlendirme",paragraphs:["Adana’da mahalle seçimi, bina niteliği ve iklim koşullarına uygun donanım kira talebini etkiler. Geniş metrekare tek başına değer göstergesi değildir; binanın yaşı, otopark, asansör ve enerji gideri önemlidir.","TCMB bölgesi Mersin’i de kapsadığı için bölgesel endeks Adana’daki tek bir mahallenin fiyatını temsil etmez. İl satış hareketini yerel kira emsalleri ve gerçek bakım maliyetiyle birlikte okuyun."],checks:["Mahalle bazında kira sürekliliği","Soğutma, yalıtım ve bina giderleri","Net alan ve yapı niteliği"]},
 antalya:{title:"Antalya için değerlendirme",paragraphs:["Antalya’da turizm, yabancı talebi ve dönemsel kiralama bazı bölgelerde fiyatları hızlı değiştirebilir. Sezonluk yüksek kira ilanını 12 aya yaymak, yıllık geliri olduğundan fazla gösterebilir.","Merkez, kıyı turizm bölgeleri ve iç ilçeler ayrı pazarlar olarak ele alınmalıdır. Site aidatı, boş sezon, kısa dönem kiralama kuralları ve profesyonel yönetim gideri net hesapta açıkça yer almalıdır."],checks:["12 aylık doluluk varsayımı","Kısa dönem kiralama mevzuatı","Aidat ve yönetim gideri"]},
 bursa:{title:"Bursa için değerlendirme",paragraphs:["Bursa’da sanayi istihdamı, üniversite talebi, merkez ilçeler ve yeni yerleşim alanları farklı fiyat dinamikleri üretir. İşe ulaşım süresi ve toplu taşıma, yalnızca kilometreden daha açıklayıcı olabilir.","Yeni konut arzının yoğun olduğu bölgelerde aynı anda çok sayıda satılık ve kiralık ilan bulunması pazarlık gücünü etkileyebilir. Eski merkez bölgelerde ise bina ve deprem incelemesi daha yüksek öncelik taşımalıdır."],checks:["Sanayi ve iş akslarına ulaşım","Yeni konut arzı ve doluluk","Bina yaşı ve teknik inceleme"]},
 kocaeli:{title:"Kocaeli için değerlendirme",paragraphs:["Kocaeli’de sanayi bölgeleri, liman faaliyetleri ve İstanbul bağlantısı güçlü talep kaynaklarıdır; ancak ilçe ve hatta vardiya güzergâhına göre ulaşım süreleri ciddi değişir. İstanbul’a yakınlık tek başına yeterli emsal değildir.","Kiracı profilini iş alanlarıyla eşleştirirken çevresel etkiler, ulaşım maliyeti ve yeni proje arzı değerlendirilmelidir. Bölgesel TCMB serisinin beş ili kapsadığı unutulmamalıdır."],checks:["İş alanlarına gerçek yolculuk süresi","Çevresel ve altyapısal koşullar","Bölgedeki yeni arz ve kira emsali"]},
 konya:{title:"Konya için değerlendirme",paragraphs:["Konya’nın geniş yerleşim yapısı merkez ilçeler arasında dahi ulaşım ve talep farkı doğurur. Üniversite, hastane, sanayi ve tramvay erişimi kiracı profilini belirleyen ana unsurlardandır.","Yeni sitelerde geniş alan ve otopark avantajı aidat ve çevre altyapısıyla birlikte değerlendirilmelidir. İl geneli satış sayısı hareketliliği gösterir; mahalle bazında fiyat doğrulaması için yeterli değildir."],checks:["Tramvay ve günlük ulaşım","Üniversite/hastane/sanayi talebi","Site aidatı ve çevre altyapısı"]},
 gaziantep:{title:"Gaziantep için değerlendirme",paragraphs:["Gaziantep’te sanayi ve ticaret kaynaklı istihdam konut talebini desteklerken nüfus hareketi ve yeniden yapılaşma bazı bölgelerde arz-talep dengesini hızla değiştirebilir. Geniş bölgesel endeks tek şehir yorumu olarak kullanılmamalıdır.","Kira emsallerinin tahsil edilebilirliği, binanın teknik durumu ve iş alanlarına erişim birlikte ölçülmelidir. Yeni ve eski yapı stokunu aynı metrekare fiyatıyla karşılaştırmak yanıltıcıdır."],checks:["Sanayi ve ticaret alanlarına erişim","Yapı stoku ve teknik durum","Yerel doluluk ve tahsilat emsali"]},
 trabzon:{title:"Trabzon için değerlendirme",paragraphs:["Trabzon’da topoğrafya, yol eğimi, manzara, merkez erişimi ve otopark aynı mahallede bile önemli fiyat farkı yaratabilir. Yabancı talebine dayalı dönemsel fiyatları sürekli yerel talep gibi değerlendirmemek gerekir.","Bölgesel TCMB serisi altı ili kapsar; bu nedenle ilan kararında yerel emsal şarttır. Nem, cephe, drenaj ve bina bakım ihtiyacı toplam sahip olma maliyetinde ayrıca incelenmelidir."],checks:["Yol, eğim ve merkez erişimi","Nem, cephe ve bakım ihtiyacı","Sürekli yerel talep ile dönemsel talep ayrımı"]}
};
