import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ExternalLink} from 'lucide-react';
import {Header,Footer} from '../../components/site-chrome';
import {PushSignup} from '../../components/push-signup';
const formatDate=(value:string)=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'long',timeZone:'Europe/Istanbul'}).format(new Date(value));
const formatTime=(value:string)=>new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(value));
export default function News(){
 const[items,setItems]=useState<any[]>([]),[sources,setSources]=useState<any[]>([]),[date,setDate]=useState(''),[source,setSource]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController(),params=new URLSearchParams();if(date)params.set('date',date);if(source)params.set('source',source);setLoading(true);setError('');fetch('/api/news'+(params.size?`?${params}`:''),{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{setItems(j.items||[]);setSources(j.sources||[])}).catch(()=>setError('Haberler şu anda alınamadı.')).finally(()=>setLoading(false));return()=>controller.abort()},[date,source]);
 const groups=useMemo<Record<string,any[]>>(()=>items.reduce((acc,item)=>{const key=formatDate(item.publishedAt);(acc[key]??=[]).push(item);return acc},{} as Record<string,any[]>),[items]);
 return <><Header back/><main className="inner ad-free-page" data-ad-free="true"><div className="page-title news-title"><p className="eyebrow">EMLAK GÜNDEMİ</p><h1>Konut kararını etkileyen gelişmeler</h1><p>Bloomberg HT, CNBC-e ve diğer yayınların konutla ilgili başlıkları kaynak gösterilerek listelenir. Tam içerik özgün yayıncıda açılır.</p></div><PushSignup/><div className="news-toolbar"><label><CalendarDays/> Tarihe göre filtrele <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Kaynak <select value={source} onChange={e=>setSource(e.target.value)}><option value="">Tüm kaynaklar</option>{sources.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{(date||source)&&<button onClick={()=>{setDate('');setSource('')}}>Filtreyi temizle</button>}</div>{loading&&<p className="data-loading">Haberler yükleniyor…</p>}{error&&<p className="error">{error}</p>}{!loading&&!error&&!items.length&&<p>Seçilen filtre için haber bulunamadı.</p>}<div className="news-groups">{Object.entries(groups).map(([day,rows])=><section key={day}><h2>{day}</h2><div className="news-list">{rows.map(item=><article key={item.slug}><div><span>{item.category} · {formatTime(item.publishedAt)}</span><h3><a href={`/haberler/haber?slug=${encodeURIComponent(item.slug)}`}>{item.title}</a></h3><p>{item.summary}</p><small>Kaynak: {item.sourceName}</small></div><a className="news-open" href={`/haberler/haber?slug=${encodeURIComponent(item.slug)}`} aria-label="Haberi aç"><ExternalLink/></a></article>)}</div></section>)}</div></main><Footer/></>
}
