import {InfoPage} from '../../components/info-page';
export default function Editorial(){return <InfoPage eyebrow="YAYIN GÜVENİ" title="Yayın ve hesaplama ilkeleri">
 <p><b>Son güncelleme: 22 Eylül 2026.</b> KonutSeyir, konut ilanı veya otomatik ekspertiz değeri üretmez. Hesaplama araçları kullanıcının girdiği tutarları açık formüllerle işler; kamu verileri yalnız kapsamı ve dönemi belirtilerek gösterilir.</p>
 <h2>Kaynak kullanımı</h2><p>Ekonomik göstergelerde TCMB EVDS, TCMB kur servisi ve TÜİK veri portalı esas alınır. Her veri kartında dönem, kaynak ve sisteme çekim zamanı gösterilir. Kaynağa erişilemediğinde son kayıt tarih belirtilerek gösterilir veya veri bulunmadığı açıkça yazılır; örnek sayı canlı veri gibi sunulmaz.</p>
 <h2>Hesaplama yöntemi</h2><p>Formüller <a href="/veri">Veri ve hesaplama yöntemi</a> sayfasında açıklanır ve otomatik testlerle doğrulanır. Mevduat stopajı yalnız faizden düşülür. Net kira hesabında boş kalma, yıllık gider ve kullanıcının girdiği vergi tutarı bir kez düşülür. Kira artışı, konut değer artışı ve enflasyon girdileri gelecek tahmini değil kullanıcı senaryosudur.</p>
 <h2>Editoryal sorumluluk</h2><p>Rehberler KonutSeyir Editoryal Ekibi tarafından kaynak, hesap tutarlılığı ve kullanıcıya açıklık bakımından gözden geçirilir. İçerikler yatırım, hukuk, vergi veya mühendislik danışmanlığı değildir. Tapu, vergi, kredi ve bina güvenliği gibi somut dosyalar yetkili uzman ve resmî kurumlarla doğrulanmalıdır.</p>
 <h2>Düzeltme politikası</h2><p>Hatalı formül, tarih, kaynak veya bağlantı bildirimi <a href="mailto:iletisim@konutseyir.com">iletisim@konutseyir.com</a> adresinden alınır. Doğrulanan hata en kısa sürede düzeltilir; içeriklerde son gözden geçirme tarihi güncellenir. Haber başlıkları özgün kaynağa bağlanır, haber sayfaları reklamsız ve arama dizini dışında tutulur.</p>
 <h2>Bağımsızlık</h2><p>KonutSeyir belirli bir ilanı, banka ürününü veya yatırım aracını satın alma yönünde önermez. İleride reklam veya ticari iş birliği kullanılırsa editoryal içerikten ayırt edilebilir biçimde işaretlenir; reklam sonucu hesaplama formülünü veya sıralamayı değiştirmez.</p>
 </InfoPage>}
