import {Header,Footer} from '../../components/site-chrome';
import {focusedTools} from '../../components/focused-tool-page';
import {Calculator,Deposit,Credit} from '../../components/calculator';

const groups=[
 {title:'Kira ve getiri',text:'Konutun kira üretme gücünü ve satın alma fiyatına göre geri dönüşünü ölçün.',items:focusedTools.filter(x=>['/hesaplama/kira-carpani','/hesaplama/net-kira','/hesaplama/reel-getiri'].includes(x.href))},
 {title:'Fiyat ve satın alma maliyeti',text:'İlanı emsallerle aynı ölçekte kıyaslayın ve satın alma sırasında oluşacak maliyetleri görün.',items:focusedTools.filter(x=>['/hesaplama/metrekare','/hesaplama/alim-maliyeti','/hesaplama/tapu-harci','/hesaplama/emlak-komisyonu'].includes(x.href))},
 {title:'Kira, tapu ve alternatif ölçüler',text:'Kira artışı, hisseli tapu ve konutun altın karşılığı gibi belirli sorular için tek amaçlı araçları kullanın.',items:focusedTools.filter(x=>['/hesaplama/kira-artis-orani','/hesaplama/hisseli-tapu','/hesaplama/altin-bazli-konut'].includes(x.href))}
];
export default function Tools(){return <><Header back/><main className="inner tools-hub">
 <div className="page-title"><p className="eyebrow">HESAP ARAÇLARI</p><h1>Tek bir soruyu hızlıca hesaplayın</h1><p>Bir konutun tamamını analiz etmek istemiyorsanız ihtiyacınız olan hesabı seçin. Her araç tek bir soruya odaklanır; böylece kira çarpanı, metrekare fiyatı, alım maliyeti veya tapu gideri için gereksiz alanlarla uğraşmazsınız.</p></div>
 <div className="tool-hub-groups">{groups.map(g=><section key={g.title}><h2>{g.title}</h2><p>{g.text}</p><div>{g.items.map(x=><a href={x.href} key={x.href}><strong>{x.label}</strong><span>Hesabı aç →</span></a>)}</div></section>)}</div>
 <section className="tool-hub-special"><div><p className="eyebrow">FİNANSMAN</p><h2>Konut kredisi hesabı</h2><p>Aylık taksit, toplam geri ödeme ve finansman maliyetini görmek için kredi aracını kullanın.</p><a href="/kredi-hesaplama">Kredi hesabını aç →</a></div><div><p className="eyebrow">BÜTÜNSEL ANALİZ</p><h2>Bir ilanı baştan sona değerlendirin</h2><p>Fiyat, kira, masraf, enflasyon ve alternatif getirileri tek modelde görmek istiyorsanız Konut Analizi'ne geçin.</p><a href="/ev-analizi">Konut analizini aç →</a></div><div><p className="eyebrow">ALTERNATİF YATIRIM</p><h2>Aynı sermayeyi karşılaştırın</h2><p>Konut, mevduat ve altını aynı başlangıç sermayesi ve aynı süre üzerinden kıyaslayın.</p><a href="/karsilastir">Karşılaştırmayı aç →</a></div></section>
 <section className="tools-editorial"><h2>Hangi aracı ne zaman kullanmalısınız?</h2><p>İlanları ilk kez eliyorsanız metrekare fiyatı ve kira çarpanı hızlı bir başlangıç sağlar. Satın almaya yaklaştığınızda tapu, emlak hizmet bedeli, tadilat ve finansman giderlerini toplam maliyete eklemek gerekir. Kiraya verme amacı varsa brüt kira yerine boş kalma ve malike ait giderleri düşen net kira hesabı daha açıklayıcıdır.</p><p>Tek araçtan çıkan sonuç ekspertiz veya yatırım tavsiyesi değildir. Bir ilan için bütün bu verileri birlikte görmek istiyorsanız araçlar arasında aynı rakamları tekrar tekrar girmek yerine Konut Analizi sayfasını kullanın. Konutun alternatif yatırım araçlarıyla bir yıllık ortak senaryosunu görmek istediğinizde ise Karşılaştır sayfasına geçin.</p></section>
 </main><Footer/></>}